### ISSUE TITLE
Control Entities Incompatible with Pehkui mod 3.7

### ISSUE THREAD

**Issue by Yuzuki68** [CommandrMoose/TardisRefined#106]
### Issue description

console controls will not work with bewitchment mod installed door to console room works, main console controls does not work, computer bank, the door toggle the Increment control and even x, y, z none seem to work. 

1. i begin with clean world with just tardis refined mod, tested console controls took flight and landed everything seems to work
2. i installed bewitchment mod no another mods. 
3. tested tardis refined mod tried taking off into flight, the control did not work, i tried door toggle it did not work, i tried another consoles non worked. 
4. i deleted bewitchment mod and tardis refined works again.

i tested with my first world and 2rd clean world with only tardis refined and bewitchment. 

bewitchment installs three another mods that it needs, feel like these another mods could be causing problems for tardis but not sure!

![lls12](https://user-images.githubusercontent.com/126754193/222374192-ea92f9f5-d150-4e65-b327-99389313d5da.png)

### Steps to reproduce

start with clean world with tardis refined, make sure controls work 

then install bwitchment and try to use any of console controls. 

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

fabic 0.14.14

### Tardis Refined version

Pre-release v0.1

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/MiGjTzNz

**Comment by kubex098** [comment]
i checked again and the issue lies actually in the newest version of the pehkui mod. after installing a version below 3.7 everything worked
