### ISSUE TITLE
Game Crashes when you die in your Tardis

### ISSUE THREAD

**Issue by trainerlord** [CommandrMoose/TardisRefined#107]
### Issue description

When you Die in your Tardis the game Crashes

### Steps to reproduce

1 enter your Tardis
2 Run /Kill
3 Game Will Crash 

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge-1.19.2-43.2.4

### Tardis Refined version

Pre-release v0.1

### Other relevant versions

Commit 07decadaa7e7ebf3fd6e16c6ca1703ca78285858 

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/N22DSCBh

**Comment by trainerlord** [comment]
Extra Note World Becomes Unsable

**Comment by Suff99** [comment]
Running the mod compiled is unsupported as things may not be finished and you’d be pointing out problems in something work in progress. 

Does this happy in the pre-release?

**Comment by trainerlord** [comment]
It is Non Replicatable in the Pre-Release it only currently effect the complied code

**Comment by Suff99** [comment]
Then we cannot accept your issue report
