### ISSUE TITLE
Can't interact with any of the buttons on the console 

### ISSUE THREAD

**Issue by ThatDuck09** [CommandrMoose/TardisRefined#111]
### Issue description

Im playing on a multiplayer server and have made a tardis but can't interact with any buttons on the console.
I followed all the steps to make it legitimately but it still doesn't work 

### Steps to reproduce
I'm using these mods
Cloth Config API
Doctor Who Regeneration
Doctor Who Weeping angels
Doctor Who WhoCosmetics
Extra Origins
Fabric API
JourneyMap
Just Enough Items
MC Dungeons Armors
MC Dungeons Artifacts
MC Dungeons Weapons
Mob Origins
Oh the Biomes you'll Go re fabricated
Origins Fabric
Origins Extra Keybinds
Pehkui
Tardis refined
Terrablender
_No response_

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.14.12

### Tardis Refined version

Pre-release v0.1

**Comment by AlienXtream** [comment]
can you please provide more information. such as other mods involved. there's at least two conflicting mods i've seen mentioned as potential causes for similar issues. this alone tells us nothing as we cant recreate the issue. we aren't psychic, you actually have to tell us whats going on for us to be able to narrow down the cause :P
