### ISSUE TITLE
Tardis is unremovable

### ISSUE THREAD

**Issue by Kuronyan** [CommandrMoose/TardisRefined#112]
### Issue description

Once grown, a tardis is unable to be deleted. the root shell sticks and will constantly regenerate itself. it can be picked up and moved, but never removed. Occasionally the block will be destroyed, but the portal remains, and when going through it, the shell will regenerate again. 

Tried deleting normally in creative, tried removing entities with console commands, tried anything i could think of and nothing would work to remove the tardis or shell.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.14.14

### Tardis Refined version

Pre-release v0.1

**Comment by CommandrMoose** [comment]
By design, you cannot destroy a root TARDIS once it has been placed. Can you please clarify what you mean by "portal"?

**Comment by CommandrMoose** [comment]
We haven't heard back from this in 2 weeks. I will close this issue for now, please feel free to reopen should you have a response.

**Comment by Kuronyan** [comment]
I apologize, I didn't see the reply in my email when it happened, I guess. I just assumed that the thread was missed. Sorry about that.

By portal, I meant the entrance into the TARDIS. Even without the block or model there, you could walk to where it was and be transported inside. 

As an admin of my own little server, not being able to remove a TARDIS at all is... rather problematic.
