### ISSUE TITLE
Immersive Portals

### ISSUE THREAD

**Issue by TogiFerretFerret** [CommandrMoose/TardisRefined#113]
### Issue description

I installed both forge and fabric versions of this mod with immersive portals  (Both from curseforge) and both times the portals were not, well immersive in the tardis, while immersive portals still worked fine. Do i need to compile this myself for it to work, or did someone do it already?

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

43.1.34

### Tardis Refined version

Pre-release v0.1

**Comment by Suff99** [comment]
What exactly is it you are reporting?

**Comment by CommandrMoose** [comment]
Immersive Portals compatibility is not available in publicly released versions of the mod. This is a feature in an upcoming updates.
