### ISSUE TITLE
Unable to use TARDIS console buttons after Terraforming

### ISSUE THREAD

**Issue by KirkMichael98** [CommandrMoose/TardisRefined#118]
### Issue description

When I got to change the interior, I cannot interact with the buttons at all. I would list all the mods I have installed but there are over 200 mods so I don't think I should list them all. I will say that it is the mods in Better Minecraft 1.19.2 Fabric edition with the addition of Bewitchment and Bewitchment plus. The game doesn't crash or anything I just can't interact with anything in the TARDIS

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader Version 0.41.17

### Tardis Refined version

Pre-release v0.1

**Comment by CommandrMoose** [comment]
We believe this has something to do with Bewitchment and our registered entities. This is fixed in the upcoming version. I will inform this thread once that version has been released.

**Comment by KirkMichael98** [comment]
Okay thank you!

**Comment by 50ap5ud5** [comment]
Seems related to the issue with Pehkui mod which is used by Bewitchment in #106.

Marking as resolved for now.
