### ISSUE TITLE
server crash: Cannot invoke "java.util.UUID.toString()" because "this.TARDIS_ID" is null

### ISSUE THREAD

**Issue by VinceKezel** [CommandrMoose/TardisRefined#131]
### Issue description

local lan multiplayer server crashes when the tardis root plant turns into the tardis root shell.

_[22:35:32] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
...
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because "this.TARDIS_ID" is null
	at whocraft.tardis_refined.common.blockentity.shell.ShellBaseBlockEntity.method_11007(ShellBaseBlockEntity.java:51) ~[TARDIS+Refined-1.19.2-0.1-PRE-RELEASE-fabric.jar:?]_

see line 2331 in linked log

### Steps to reproduce

Put a tardis root plant on magma and wait for it to grow. about 1 second after it turns into the tardis root shell the server crashes. The work-around for us for now is to use creative to place the root shell. The crash only happens when the plant is turning into the shell.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader 0.14.19

### Tardis Refined version

Pre-release v0.1

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/Znk6RwnG

**Comment by 50ap5ud5** [comment]
Thanks for reporting this. Can you reproduce this issue if Tardis Refined is the only mod installed?

**Comment by VinceKezel** [comment]
Ah, I should have tested that first. With only Tardis Refined the plant to shell works without any crash. There's no issue with your mod. Later this week I am going to try to narrow it down to which other mod is creating the incompatibility.
