### ISSUE TITLE
Brocken Demat

### ISSUE THREAD

**Issue by LordAret** [CommandrMoose/TardisRefined#136]
### Issue description

I ignored Danger Zone and crashed, i attuned my tardis key and then used it on landing pad, tardis started demat even that its brocken.

### Steps to reproduce

1. Start demat and then ignore all flight event.
2. TARDIS shoul crash if you did everything right, now use your key on monitor and go outisde.
3. Then place near Landing Pad and click it with key.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 43.2.0

### Tardis Refined version

v1.0

**Comment by CommandrMoose** [comment]
Thanks for the catch! We'll have this updated in the next build
