### ISSUE TITLE
Game crashes after exiting the TARDIS Dimension after placing the Terraformer

### ISSUE THREAD

**Issue by Dragonrage22** [CommandrMoose/TardisRefined#137]
### Issue description

Been playing a custom pack a friend and I threw together. after finding and growing my TARDIS. I go to start Terraforming it and when leaving the dimension for it to update. The game crashes to the Launcher

### Steps to reproduce

1. Enter Tardis Dimension
2. Build Terraformer Multiblock
3. Exit the Dimension
4. Crash

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader 0.14.19

### Tardis Refined version

Pre-release v0.1

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://gist.github.com/Dragonrage22/a2ca7e6f3e472b15cc05a929c81b41b1

**Comment by 50ap5ud5** [comment]
Thanks for reporting this. Can you reproduce this issue if Tardis Refined is the only mod installed?

**Comment by zipzapzopzip** [comment]
same issue for me but I am fairly sure it is a mod incompatibility causing it.

**Comment by KamijouTMM** [comment]
Can only reproduce if immersive portals is loaded

**Comment by Dragonrage22** [comment]
Been unable to recreate issue without any other mods. Tried a handful of different mods an unable to find the issue.

**Comment by Suff99** [comment]
I consider this resolved as it is to do with a mod trying to access our old control entity code for attributes, this is solved in V1 as we not longer use LivingEntities for the controls
