### ISSUE TITLE
Client Hangs when entering new TARDIS

### ISSUE THREAD

**Issue by KamijouTMM** [CommandrMoose/TardisRefined#138]
### Issue description

We wanted to start fooling around with the mod. We grew the TARDIS and tried entering it. I entered first and my game got stuck on the 'Loading Terrain' screen, had to close the game with task manager. After that we entered the same tardis as before and it worked fine until we tried to exit after we built the terraformer and the first person to go through had this same thing happen. We tried again and it still crashed. We tried without Immersive Portals and it worked fine, but not with it, which is a bummer.

### Steps to reproduce

1. Grow a tardis
2. Try entering
3. hangs on 'loading terrain'
4. quit
5. rejoin
6. enters just fine, start terraforming
7. hangs on loading terrain when exiting
8. works fine after the terraforming process

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

43.2.10

### Tardis Refined version

v1.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://mclo.gs/I8nIRb7    - client
https://mclo.gs/q1lG1kH  - server

**Comment by Suff99** [comment]
Issues with the forge version of Immersive Portals has been reported a few times now - we're looking into the issue as we wish to resolve 

Is it possible for you to validate this doesn't happen on fabric?

**Comment by KamijouTMM** [comment]
Only happens on forge

**Comment by Suff99** [comment]
Creating a investigation issue for this situation, please go to https://github.com/CommandrMoose/TardisRefined/issues/148
