### ISSUE TITLE
Tardis IS removable

### ISSUE THREAD

**Issue by DaPuffer** [CommandrMoose/TardisRefined#140]
### Issue description

Tardis (and other unbreakable blocks) can be removed with console configurators.

### Steps to reproduce

1. Get a Tardis, a root shell or any other block that should usually be unbreakable
2. Place a console configurator
3. Use the configurator while holding shift
4. The block gets removed,but if it is a root shell,the root shell will drop.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge Version 43.2.0

### Tardis Refined version

v1.0

**Comment by CommandrMoose** [comment]
This logic was updated in our correct v1 release, can you please verify that this is specifically an issue from the V1 release version found on Modrinth?

**Comment by CommandrMoose** [comment]
We've internally confirmed this bug. Thank you for the report.
