### ISSUE TITLE
Broken static and pattern manipulator subtitles

### ISSUE THREAD

**Issue by DaPuffer** [CommandrMoose/TardisRefined#141]
### Issue description

When you use the Pattern manipulator or click on a different desktop configuration,broken subtitles show

![subtitle2](https://user-images.githubusercontent.com/132820752/236675357-d8503796-b846-445a-a842-51489e85d98d.png)

![subtitle 3](https://user-images.githubusercontent.com/132820752/236675522-ef90d01e-8c23-4b9c-89d7-7611c4325379.png)

### Steps to reproduce

1. Use the Pattern manipulator or switch the desktop configuration in the data bank
2. Witness the subtitles being broken

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge Version 43.2.0

### Tardis Refined version

v1.0

**Comment by CommandrMoose** [comment]
Good catch! We'll have this updated for the next build :)

**Comment by Suff99** [comment]
Resolved
