### ISSUE TITLE
Even more subtitle problems!

### ISSUE THREAD

**Issue by DaPuffer** [CommandrMoose/TardisRefined#143]
### Issue description

Subtitles for take off,landing and flight are like this:
![subtitle22](https://github.com/CommandrMoose/TardisRefined/assets/132820752/016a4647-5794-4532-9890-854b069f5c1b)
![subtitle11](https://github.com/CommandrMoose/TardisRefined/assets/132820752/5f593ff9-b8d9-4abf-8418-f66c2a111ecc)
![subtitle33](https://github.com/CommandrMoose/TardisRefined/assets/132820752/d0c361af-edff-4879-9513-5aac12a70679)

### Steps to reproduce

1. Turn on the subtitles
2. Get any of the listed above sounds
3. See the name of the subtitle instead 

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge Version 43.2.0

### Tardis Refined version

v1.0

**Comment by Suff99** [comment]
Already been addressed
