### ISSUE TITLE
[Bug] Terraformer not working

### ISSUE THREAD

**Issue by AlienXtream** [CommandrMoose/TardisRefined#147]
### Issue description

if the player leaves the world after generating the tardis interior BUT before terraforming, the terraformer will become non functional for that tardis going forward. this issue occurs with just tardis refined, though i initially suspected it to be related to immersive portals. its only because a bug with IP causes a reload to be required, and thus triggering this.

### Steps to reproduce

create tardis.
enter for first time.
save and quit.
reload.
try to use terraformer

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

forge 43.2.11

### Tardis Refined version

v1.0

**Comment by Suff99** [comment]
Creating a investigation issue for this situation, please go to https://github.com/CommandrMoose/TardisRefined/issues/148
