### ISSUE TITLE
Sonic Screwdriver [Addition]

### ISSUE THREAD

**Issue by TogiFerretFerret** [CommandrMoose/TardisRefined#153]
### Issue description

As a loooooong time doctor who fan, I will say so far this mod is WAY better than The New Tardis mod and Dalek mod. But, it is lacking the sonic screwdriver.

### Minecraft version

1.19.4 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Not Important

### Tardis Refined version

v1.0

**Comment by Suff99** [comment]
This is neither a crash nor a big. Suggestions go to the mods discord - your suggestion has already been accomplished in WhoCosmetics
