### ISSUE TITLE
[Quilt] Crash not long after world loads on server

### ISSUE THREAD

**Issue by waddon1** [CommandrMoose/TardisRefined#155]
### Issue description

Server crashes just after startup.

### Steps to reproduce

1. Start Server
2. Server starts and world finishes loading
3. Server crashes

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

0.19.1

### Tardis Refined version

v1.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/ak3Fd5ap

**Comment by Suff99** [comment]
Please recreate the issue on a supported mod loader and leave a comment if the issue persists
