### ISSUE TITLE
TARDIS refuses to terraform- and will not let you re-enter shell once you leave.

### ISSUE THREAD

**Issue by OutcastsAnonymous** [CommandrMoose/TardisRefined#156]
### Issue description

I'm running on Fabric 1.19.2 with a few other mods installed along-side it, so I'm assuming it's a compatibility issue that I'm not aware of that's causing it- but after building the terraforming structure, it refused to activate. Additionally, as mentioned in the title, leaving the shell after entering the TARDIS results in it not letting you back in; terraformer or no. The exterior also never changed, even after half-an-hour.

Attempting to enter the TARDIS using a command resulted in me being kicked to the front door, still in the Overworld.

I replicated this bug without building the terraformer structure after my first run in with it, so I'm assuming that it's a separate issue to that, and that I just so happened to stumble into them both at the same time.

A second replicable bug I've encountered (that I think may be the cause of the first one) is that the game will crash when attempting to enter the TARDIS for the first (and the only allowed) time. I have only managed to replicate this on TARDISes that have been grown using modified tick speed- however as I type this I am manually growing another the normal way to see if the same result happens. After logging back in after the crash, you spawn inside the TARDIS- meaning it's not the dimension itself that's crashing the game, it's the movement between dimensions.

I am playing with:
3dskinlayers-fabric-1.5.2-mc1.19.1.jar
AdditionalEnchantedMiner-1.19-fabric-19.1.753.jar
ad_astra-fabric-1.19.2-1.12.6.jar
AE2WTLib-12.9.5.jar
akashictomeoftools-1.3.8.jar
AmbientSounds_FABRIC_v5.2.13_mc1.19.2.jar
antighost-1.19.1-fabric0.58.5-1.1.5.jar
appleskin-fabric-mc1.19-2.4.1.jar
appliedenergistics2-fabric-12.9.5.jar
architectury-6.5.85-fabric.jar
armourersworkshop-fabric-1.19.2-2.0.0-beta.26.jar
AttributeFix-Fabric-1.19.2-17.2.6.jar
autohud-3.2.1+1.19.1.jar
auto_third_person-fabric-1.19.2-2.jar
azurelib-fabric-1.19.2-1.0.23.jar
balm-fabric-1.19.2-4.5.7.jar
bclib-2.1.7.jar
better-end-2.1.6.jar
better-nether-7.1.4.jar
BetterAdvancements-Fabric-1.19.2-0.2.2.142.jar
BetterF3-4.0.0-Fabric-1.19.2.jar
BetterThirdPerson-Fabric-1.19-1.9.0.jar
blur-2.6.0.jar
BOMD-1.4.6-1.19.2.jar
Bookshelf-Fabric-1.19.2-16.3.20.jar
botarium-fabric-1.19.2-1.8.2.jar
BridgingMod-1.19.2-1.2.0.jar
BuildingWands-mc1.19.2-2.6.6-release-fabric.jar
CameraOverhaul-1.4.0-fabric-universal.jar
cardinal-components-api-5.0.2.jar
cave_dust-1.2.0.jar
chisel-1.4.7+1.19.2.jar
cloth-config-8.2.88-fabric.jar
Clumps-fabric-1.19.2-9.0.0+14.jar
collective-1.19.2-6.61.jar
completeconfig-2.1.0.jar
configured-fabric-2.0.0-1.19.2.jar
Controlling-fabric-1.19.2-10.0+7.jar
cookingforblockheads-fabric-1.19.2-13.3.2.jar
CorgiLib-fabric-1.19.2-1.0.0.34.jar
CosmeticArmor-1.19-1.4.2.jar
create-fabric-0.5.1-b-build.1079+mc1.19.2.jar
CreativeCore_FABRIC_v2.9.4_mc1.19.2.jar
CustomSkinLoader_Fabric-14.16.jar
DarkUtilities-Fabric-1.19.2-13.1.9.jar
Decorative Blocks-fabric-1.19.2-3.0.0.jar
delightful-creators-1.1.1.jar
Ding-1.19.2-Fabric-1.4.0.jar
doubledoors-1.19.2-4.5.jar
dropz-fabric-2.2.0+1.19.2.jar
dynamiccrosshair-5.6.1+1.19.2-fabric.jar
EnchantmentDescriptions-Fabric-1.19.2-13.0.14.jar
enderchests-fabric-1.19-1.1.1b.jar
entangled-1.3.14-fabric-mc1.19.2.jar
entityculling-fabric-1.6.1-mc1.19.2.jar
entity_model_features_fabric_1.19.2-0.2.9.jar
entity_texture_features_fabric_1.19.2-4.4.4.jar
enviromats-fabric-1.19-2.1.1.0.jar
expandedstorage-8.3.4+1.19.2-fabric.jar
explorify-fabric-1.19-1.3.0.jar
ExtendedDrawers-1.4.1+mc.1.19.2.jar
FABRIC - TARDIS Refined v1-1.19.2.jar
fabric-api-0.76.0+1.19.2.jar
fabric-language-kotlin-1.9.5+kotlin.1.8.22.jar
fabric-language-scala-1.1.0+scala.2.13.6-fat.jar
factory-blocks-mod-1.0.1+1.19.jar
farmers-delight-fabric-1.19.X-1.3.9.jar
farsight-fabric-1.19.2-3.5.jar
fastfurnace-1.19.2-5.jar
ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar
fusion-1.0.0b-fabric-mc1.19.2.jar
geckolib-fabric-1.19-3.1.40.jar
HWGMod-1.19.2-1.4.10.jar
immersive-portals-2.2.5-mc1.19.2-fabric.jar
indium-1.0.9+mc1.19.2.jar
iris-mc1.19.2-1.4.0.jar
IronChests-1.7.7.jar
ironchests-3.1.2-fabric.jar
Jade-1.19.1-fabric-8.7.3.jar
jamlib-0.6.0+1.19.jar
jei-1.19.2-fabric-11.6.0.1015.jar
journeymap-1.19.2-5.9.7-fabric.jar
JustEnoughProfessions-fabric-1.19.2-2.0.2.jar
JustEnoughResources-Fabric-1.19.2-1.2.2.200.jar
kubejs-create-fabric-1902.2.4-build.5.jar.disabled
kubejs-fabric-1902.6.0-build.142.jar.disabled
lambdynamiclights-2.2.0+1.19.2.jar
laserbridges-1.19.2-1.jar
LeavesBeGone-v4.0.1-1.19.2-Fabric.jar
light-overlay-7.0.0.jar
litematica-fabric-1.19.2-0.12.7.jar
lithium-fabric-mc1.19.2-0.11.1.jar
logprot-fabric-1.19-2.0.jar
lootr-1.19-0.4.27.67.jar
magehand-1.1.3-1.19.2.jar
malilib-fabric-1.19.2-0.13.0.jar
mcpitanlibarch-1.6.9-1.19.2-fabric.jar
mcw-furniture-3.1.1-mc1.19.2fabric.jar
megacells-fabric-1.5.3-1.19.2.jar
memoryleakfix-fabric-1.17+-1.0.0.jar
midnightlib-fabric-1.0.0.jar
moonlight-1.19.2-2.2.38-fabric.jar
MouseTweaks-fabric-mc1.19-2.22.jar
not-mutually-exlusive-1.19.2.jar
notenoughanimations-fabric-1.6.2-mc1.19.2.jar
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.3.jar
openblockselevator-0.0.3-1.19.X.jar
OpenSimpleFrames-1.0.6.jar
paladin-furniture-mod-1.1.1-fabric-mc1.19.jar
Patchouli-1.19.2-77-FABRIC.jar
Pehkui-3.7.5+1.14.4-1.20.jar
PigPen-Fabric-1.19.2-11.1.2.jar
PipePlus-1.19.2-0.5.0.jar
polymorph-fabric-0.46.1+1.19.2.jar
PuzzlesLib-v4.4.2-1.19.2-Fabric.jar
Quark-Crystals-1.19.2-2.3.2.jar
rayon-fabric-1.7.1+1.19.2.jar
replaymod-1.19.1-2.6.10.jar
repurposed_structures_fabric-6.3.24+1.19.2.jar
resourcefulconfig-fabric-1.19.2-1.0.20.jar
resourcefullib-fabric-1.19.2-1.1.24.jar
rhino-fabric-1902.2.2-build.268.jar
right-click-harvest-3.2.2+1.19.x-1.20.1-fabric.jar
Runelic-Fabric-1.19.2-14.1.4.jar
shetiphiancore-fabric-1.19-1.3.4b.jar
ShoulderSurfing-Fabric-1.19.2-2.3.2.jar
simplemagnets-1.1.9-fabric-mc1.19.2.jar
simplepipes-all-0.8.2.jar
simplylight-fabric-1.19-1.4.3.jar
skylorlib-1.5.1.jar
SmartBrainLib-fabric-1.19.2-1.9.jar
smoothboot-fabric-1.19-1.7.1.jar
sodium-extra-0.4.16+mc1.19.2-build.90.jar.disabled
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
soundphysics-fabric-1.19.2-1.0.18.jar
spark-1.10.37-fabric.jar
starlight-1.1.1+fabric.ae22326.jar
Steam_Rails-1.2.6+fabric-mc1.19.2.jar.disabled
supermartijn642configlib-1.1.6-fabric-mc1.19.jar
supermartijn642corelib-1.1.9f-fabric-mc1.19.2.jar
supplementaries-1.19.2-2.3.19-fabric.jar
tempad-fabric-1.19.2-1.4.5.jar
TerraBlender-fabric-1.19.2-2.0.1.136.jar
Terralith_1.19.3_v2.3.8.jar
theprinter-1.0.2+1.19.jar
trashcans-0.0.2-1.19.X.jar
travelers-backpack-1.19.2-8.2.23.jar
trinkets-3.4.2.jar
tweakeroo-fabric-1.19.2-0.14.3.jar
valkyrielib-fabric-1.19-4.0.1.1.jar
vanilla-refresh-1.4.14a.jar
VisualWorkbench-v4.2.4-1.19.2-Fabric.jar
worldedit-mod-7.2.12.jar
YungsApi-1.19.2-Fabric-3.8.9.jar
YungsBetterDesertTemples-1.19.2-Fabric-2.2.2.jar
YungsBetterDungeons-1.19.2-Fabric-3.2.1.jar
YungsBetterMineshafts-1.19.2-Fabric-3.2.0.jar
YungsBetterNetherFortresses-1.19.2-Fabric-1.0.5.jar
YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0.jar
YungsBetterStrongholds-1.19.2-Fabric-3.2.0.jar 

### Steps to reproduce

1. Grow TARDIS with modified tick speed.
2. Enter TARDIS.
3. Crash.
4. Log back in.
5. Build the Terraformer and its structure. (They should not activate.)
6. Leave the TARDIS.
7. Profit.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.14.21

### Tardis Refined version

v1.0

**Comment by CommandrMoose** [comment]
Please send the crash report, we can't do anything without it.

**Comment by OutcastsAnonymous** [comment]
Finished the natural growth test. The results? Same crashing issue. Meaning it has nothing to do with the tick speed, the game just doesn't like me. Here's the provided crash report for that:  https://pastebin.com/g8bg4rm5

I'd provide you with the crash report for the issue of not being allowed back in the TARDIS, but that doesn't crash the game, so there isn't one.

**Comment by CommandrMoose** [comment]
I'm willing to say you're right about the double whammy issue here. From the looks of things, this is an issue caused by the mod Rayon crashing. Without knowing what they're doing I'd say its crashing because its not expecting a new dimension to be created. The crash is causing the TARDIS to not register correctly, not allowing you to terraform - basically the growth is a dead dimension.

I recommend you try without Rayon and see if the issue persists. You will most likely have to create a new TARDIS.
Thanks for the report and I appreciate the work you've done for it :).

**Comment by OutcastsAnonymous** [comment]
Removing Rayon did seem to fix the issue- however I can't help but be confused as to why considering it's a mod that effects the physics engine and has nothing to do with dimensions. Either way, like I said, turning it off fixed all my issues- meaning it was a compatibility issue after all.

Just for the sake of documenting it, I took a video of the issue before the fix and attached it to this post. It's not problem, and I'm just glad to help; love DW and the work you've done so far!

https://github.com/CommandrMoose/TardisRefined/assets/67887861/470cfc89-6c45-446e-89c4-3e5fc050dc60
