### ISSUE TITLE
Crash on Tardis Enter

### ISSUE THREAD

**Issue by biggerontheinside117** [CommandrMoose/TardisRefined#157]
### Issue description

so my tardis finished growing but when i entered my game crashed

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

fabric loader version 0.14.21-1.19.2

### Tardis Refined version

v1.0

**Comment by CommandrMoose** [comment]
We cannot do anything without a crash report. Please comment a paste bin with the log in order for us to move forward with this.

**Comment by AlienXtream** [comment]
appears possibly related to this (or at least similar funkyness). please provide crash report and/or log file for analasys and confirmation as, to my knowledge, this is only documented on the forge version.
https://github.com/CommandrMoose/TardisRefined/issues/148
