### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by MagmaBro123** [CommandrMoose/TardisRefined#161]
### Issue description

Entering flight will sometimes cause a crash.

### Steps to reproduce

Start flying a TARDIS.

### Minecraft version

1.19.4 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

![image](https://github.com/CommandrMoose/TardisRefined/assets/51277766/469ea923-642f-4c1b-9e24-b24527eba170)

### Tardis Refined version

v1.0

### Other relevant versions

N/A. Crash report says this mod is the issue.

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/Y6PBV56M

**Comment by 50ap5ud5** [comment]
Thank you for reporting this. This is related to #160 and #154 which we will look into fixing for the next version.
