### ISSUE TITLE
No way to get out of the tardis when the door is destroyed.

### ISSUE THREAD

**Issue by loghunger** [CommandrMoose/TardisRefined#190]
### Issue description

When the door out of a tardis is broken and a player is inside they can not leave.  A few suggestions to fix it are:
1. When changing the desktop configuration the console make it force any players in the Tardis out of it like when orrignally terraforming it.
2. Add a way to get a replacement door from the console.
3. When changing the external shell configuration make the interior door regenerate.

### Steps to reproduce

1. Create a tardis and enter. 2. Put a tnt block by the tardis door from inside and light it. 3. Let it explode and destroy the door you are now stranded.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 1.19.2-43.3.5

### Tardis Refined version

v1.0

**Comment by 50ap5ud5** [comment]
You can craft a TARDIS door. Have you tried doing so and placing it down?

**Comment by loghunger** [comment]
Yes this works in creative however when in survival if you do not have the resources on you there is no way to get them when you are in a tardis.

**Comment by Jeryn99** [comment]
@50ap5ud5 Perhaps the ARS egg should hand these out for free? Their not a item that the user really gains or looses much from

**Comment by 50ap5ud5** [comment]
> @50ap5ud5 Perhaps the ARS egg should hand these out for free? Their not a item that the user really gains or looses much from

I think it's a good idea to add a way to provide the door for free. I'm not sure if we want to use the ARS Egg specifically though. However, if we do this, the crafting recipe will become redundant.

**Comment by leafreynolds** [comment]
That might be fine though. The Tardis in canon changes to the needs of the inhabitants. Getting a door so they can exit is a pretty big need, and they're only really useful in the tardis specifically anyway.

**Comment by CommandrMoose** [comment]
@Jeryn99 Let's add this to the terminal changes as an emergency eject.

**Comment by loghunger** [comment]
Yes, it is still an issue, in the case that the door within the tardis interior is destroyed it is impossible to leave the tardis without dying, and if the door to the corridors is also destroyed there is no way to leave the tardis.   To fix this my three original suggestions would still work and be excellent solutions to the problem.

**Comment by Jeryn99** [comment]
@CommandrMoose As we said, we forgot about this - 2.0.1 also?
