### ISSUE TITLE
Tardis chunks showing in the overworld with the Distant Horizons mod

### ISSUE THREAD

**Issue by Dragon36man** [CommandrMoose/TardisRefined#191]
### Issue description

when using Tardis refined on a server with Distant Horizons client side the fake chunks display the chunks that represent the Tardis's interiors resulting in a mass of chunks appearing as massive cliffs of stone near spawn.
![2024-01-03_13 11 22](https://github.com/Suff99/TardisRefined/assets/155532750/cc86efba-bc67-45f4-99f2-1e1d909352a3)

### Steps to reproduce

Enter your taidis then, exit your tardis, look towards 0 0 and you will see it if 0 0 is rendered with Distant Horizons fake chunks.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 43.3.5

### Tardis Refined version

v1.0

### Other relevant versions

using Distant Horizons Ver 2.0.1 with the mod is the main issue.
modpack that I am using is linked here https://modrinth.com/modpack/more-minecraft-with-tardis-refined

**Comment by Jeryn99** [comment]
I feel this may be something you would need to take up with them, we will investigate this incase there is something strange we do but other than creating dynamic dimensions - we shouldn't be doing anything to upset chunks like that

**Comment by Dragon36man** [comment]
It is on a server dose not seem to happen on single player. Might be how distant horizons works on a server where fake chunks are generated in the same fashion as making a map in minecraft

**Comment by Dragon36man** [comment]
Seems on the server in order to clear the glitched chunks just explore where the glitched chunks are and they go away until you enter a tardis again but it only shows in and around the area of 0,0.

**Comment by Dragon36man** [comment]
It is mostly a visual bug between distant horizons and tardis refined. Kinda like overlaping maps or data showing both at the same time. While not really affecting anything else

**Comment by Jeryn99** [comment]
Have you created a issue report on their repo?

**Comment by CommandrMoose** [comment]
Haven't heard much back from this. If you've created an issue with them, feel free to reopen this.
