### ISSUE TITLE
Bug when the server is restarted

### ISSUE THREAD

**Issue by Fabricio32109** [CommandrMoose/TardisRefined#194]
### Issue description

Just that, the TARDIS works perfectlly, but when the server is restarted it stops working and look like this. Something interesting is that I went to the TARDIS dimension and the room where everything is supposed to be is gone
![Captura](https://github.com/Suff99/TardisRefined/assets/51131917/37bdf8af-bc06-40bd-a083-fd25fddfd256)

### Steps to reproduce

Shut down the server
Turn on the server

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

forge-43.3.7

### Tardis Refined version

v1.0

**Comment by Jeryn99** [comment]
Fixed in 1.20
