### ISSUE TITLE
Can't sleep aboard TARDIS

### ISSUE THREAD

**Issue by sableseyler** [CommandrMoose/TardisRefined#198]
### Issue description

If you place a bed (or a modded sleeping bag) in a TARDIS, you are unable to sleep. Right clicking the bed does nothing. No error message is produced. Reproduced on a barebones instance in a new superflat world with just Fabric loader, Fabric API 0.76.1+1.19.2, and TARDIS Refined 1.0.1 installed.

### Steps to reproduce

1. Enter any TARDIS
2. Place down a bed
3. Attempt to "use" the bed (default right-click)
4. Observe that nothing happens

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

0.15.3

### Tardis Refined version

v1.0

**Comment by sableseyler** [comment]
With the excellent help of Jeryn on the Discord, this has been figured out. It's prevented by the `has_skylight`  setting [here](https://github.com/Suff99/TardisRefined/blob/bec2a83d7dc66983c1f3c385409ae71c256f5868/common/src/main/resources/data/tardis_refined/dimension_type/tardis.json#L8).

**Comment by pseudoble** [comment]
Is this toggleable via a datapack or something? My bed explodes on the tardis. Is this how I make it safe and set my spawn point there?

**Comment by Jeryn99** [comment]
https://discord.com/channels/1054629302152478730/1251253986514964640
