### ISSUE TITLE
Changing interior to Toyota crashes server

### ISSUE THREAD

**Issue by oldtrain1** [CommandrMoose/TardisRefined#200]
### Issue description

My friend on our modded survival world grew a Tardis, terraformed and everything fine. I already made one with ease and changed the interior on my own, with the only bug being a Tardis exterior where the Coral was placed, but that's only a minor bug. The real problem started when my friend made his Tardis. He made it, went inside and changed the exterior to Phone Booth and the interior to Future Nostalgia. He didn't like it so he changed to Toyota, where he said "the tp portal blocks at the door were gone", so he logged out and back in to see if it would fix it. It did not and now the server is in an infinite loop of crashing on startup.

### Steps to reproduce

1. Create Tardis via normal means (grow coral, terraform)
2. Go inside
3. Change exterior to Phone Booth, interior to Future Nostalgia
4. Go outside
5. Go inside
6. Change to Toyota
7. Leave game
8. Joining back makes the server crash completely

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge Version 43.3.0

### Tardis Refined version

v1.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/CvvV8j13

**Comment by CommandrMoose** [comment]
This seems to be an issue to do with FerriteCore ((Neo)Forge). can you confirm the issue does not occur when the mod isn't installed?

**Comment by Jeryn99** [comment]
No, this is us - we didn’t check for whether a block has a state before trying to edit that state, it’s from your old generation code 

Happens when the shell block is being told to regenerate but no shell block is present 

may be fixed now
