### ISSUE TITLE
Create's redstone links do not function in TARDIS dimension

### ISSUE THREAD

**Issue by sableseyler** [CommandrMoose/TardisRefined#204]
### Issue description

Create provides a "Redstone Link" item for wireless redstone engineering. It allows you to configure one link as broadcasting and another as receiving (optionally even on specific frequencies), and then whatever redstone signal goes into the broadcasting link is output by the receiving link.

Unfortunately, this item does not work in the TARDIS dimension. It simply fails to receive, producing this error message:

```
[19:38:20] [Server thread/WARN]: Tried to Access unprepared network space of tardis_refined:tardis
```

I'm not sure whether this is caused on Create's side or y'alls, but I'd quite appreciate being able to fix it, if possible.

### Steps to reproduce

1. Acquire a TARDIS
2. Enter it
3. Optionally terraform it, happens either way
4. Place a redstone lamp (or other block that does noticeable things when receiving a redstone signal) with a redstone link on top
5. Sneak-Use (default shift-right-click) this link to put it in receiving mode
6. Several paces away, place another link, and a lever adjacent to it
7. Flip the lever
8. Observe that the lamp (or other redstone-sensitive block) does not activate

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

0.15.3

### Tardis Refined version

v1.0

### Other relevant versions

Create 0.5.1-c-build.1160

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://gist.github.com/seylerius/4f483de0933bfb35b342b556afc10be1

**Comment by Jeryn99** [comment]
Developer Note:
Seems to have been brought up in the Create Discord on this occasion and another, both times users were not responded to 

![image](https://github.com/Jeryn99/TardisRefined/assets/36424503/c59a13aa-4578-491d-ac60-8e13e116e739)
![image](https://github.com/Jeryn99/TardisRefined/assets/36424503/9521cd6b-621c-415f-b741-055fab11732d)

Not sure if this is on us or on create? The way we dynamically create dimensions could be proving problematic but then I would expect this issue to happen within other mods aswell that use a similar approach
