### ISSUE TITLE
Game crash with immersive portals upon opening tardis doors

### ISSUE THREAD

**Issue by Mobhunter101** [CommandrMoose/TardisRefined#227]
### Issue description

with both fabric tardis refined 1.0 and 1.01 and immersive portals installed the game crashes after opening the doors of the tardis

### Steps to reproduce

1. have both fabric tardis refined and latest 1.19.2 immersive portals installed
2. grow the tardis and terraform it
3. wait for it to terraform and open the doors, game crash

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric-loader-0.15.10-1.19.2

### Tardis Refined version

v1.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/rN3P7uqH

**Comment by CommandrMoose** [comment]
Is this the full crash report file?

My first recommendation is to attempt this with Sodium. Right now the crash report doesn't give us much to work with.

**Comment by Mobhunter101** [comment]
I will try sodium, this is the full crash report, however I tried uninstalling the immersive portals mod, I went into the tardis and changed it to the copper interior, then reinstalled the portals mod. the game loaded and then while inside the tardis i closed and opened the door, causing another crash, this time it mentions a banner instead of a magma block
[crash-2024-04-23_23.46.38-client.txt](https://github.com/WhoCraft/TardisRefined/files/15087706/crash-2024-04-23_23.46.38-client.txt)

**Comment by Mobhunter101** [comment]
Happy to report that immediately after installing sodium the crashing has stopped i will continue to test

**Comment by Jeryn99** [comment]
Cannot accept this issue as it is a issue with IP and not our end
