### ISSUE TITLE
Forge 1.19.2 crashes when clicking "play" on the Minecraft Launcher

### ISSUE THREAD

**Issue by DalekPratt1963** [CommandrMoose/TardisRefined#232]
### Issue description

So I downloaded the Forge 1.19.2 Launcher so I could play TardisRefined, but it crashes when I launch!
I made sure to download Java and install it into the Minecraft Launcher, and I'm using the paid Minecraft Java game version. (This means I have access to use mods *Like the Dalek Mod for reference*)

Here is the Crash Code I recieved:
Exit Code: 1

(Here is a screenshot of my Launcher after I tried launching)
![image](https://github.com/WhoCraft/TardisRefined/assets/168283943/5ca18afd-661a-426a-bd6f-98d9aebdaa4e)

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge Version 43.3.13

### Tardis Refined version

v1.0

**Comment by CommandrMoose** [comment]
Without a crash log we can't do much. I've found that this can be the cause of a mod preventing actual initialization or you're needing to update Forge.

**Comment by DalekPratt1963** [comment]
> Without a crash log we can't do much. I've found that this can be the cause of a mod preventing actual initialization or you're needing to update Forge.

Yeah I tried to find a crash log, but didn't find one.
I got the curseforge app to see if I could find one there, but no luck either... I'll have to try and see what is going on.

**Comment by CommandrMoose** [comment]
Has it output a latest.txt? That might have what we need

**Comment by DalekPratt1963** [comment]
> Has it output a latest.txt? That might have what we need

Not from what I can see... I'm only seeing these things when I click the minecraft folder inside the curseforge folder.

Downloads -> Empty Folder
Install -> Versions & Minecraft Launcher (Versions folder is empty)
Instances -> Empty Folder

**Comment by DalekPratt1963** [comment]
Wait a minute, I clicked the minecraft launcher and it added more folders. This may help get us somewhere!

**Comment by DalekPratt1963** [comment]
So uh...

**I'm an idiot because I didn't even think about removing the Dalek Mod from my mods folder, which is a mod for an older version of MC...**

So just doing that fixed everything.
