### ISSUE TITLE
launcher crashes when mod is enabled

### ISSUE THREAD

**Issue by CrayzKato** [CommandrMoose/TardisRefined#252]
### Issue description

i created a new instance on the modrinth app, 1.20.2 neoforge

when i booted it up with no mods it worked fine

when i booted it up with tardis refined it crashes before getting to the start screen

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Neoforge

### Mod Loader version

Neoforge version 20.2.88

### Tardis Refined version

v2.0

[crash-2024-05-10_18.20.47-client.txt](https://github.com/WhoCraft/TardisRefined/files/15280587/crash-2024-05-10_18.20.47-client.txt)

_No response_

**Comment by Jeryn99** [comment]
Where is the crash report?

**Comment by CrayzKato** [comment]
one moment while i get it

**Comment by CrayzKato** [comment]
[10May2024 18:18:41.117] [Render thread/ERROR] [net.neoforged.neoforge.registries.GameData/]: Rolling back to VANILLA state
[10May2024 18:18:41.801] [Render thread/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID c5b0fec2-711d-4254-9e99-92b905cd7294
[10May2024 18:18:41.803] [Render thread/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID de7b9068-545a-4329-8a33-59ec8cfe7d27

**Comment by CommandrMoose** [comment]
Please send that crash report file. We can't do anything with this

**Comment by Jeryn99** [comment]
This is not a crash report, this is a partial error from one

Please drag the file into the comments box and upload it in full

**Comment by CrayzKato** [comment]
posted in full

**Comment by CrayzKato** [comment]
or would you prefer the actual file?

**Comment by Jeryn99** [comment]
the file

**Comment by CrayzKato** [comment]
found the file

**Comment by Jeryn99** [comment]
Closing this as someone has reported it correctly. 

https://github.com/WhoCraft/TardisRefined/issues/253
