### ISSUE TITLE
Failure to launch on NeoForge

### ISSUE THREAD

**Issue by Coolstriker64** [CommandrMoose/TardisRefined#253]
### Issue description

The game failed to launch, crashed during start up.
There were no other mods installed, and no other programs deliberately interfering with minecraft.

### Steps to reproduce

Unknown. I simply attempted to launch the game with the 2.0 version, and no other mods.

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Neoforge

### Mod Loader version

20.2.88

### Tardis Refined version

v2.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/uLxb8nD5

**Comment by Jeryn99** [comment]
We're looking into it - it's a NeoForge only issue.

**Comment by Jeryn99** [comment]
https://github.com/WhoCraft/TardisRefined/commit/b88345c71411f6a1553599203bc947a3f382aa6a

Resolved in this commit
