### ISSUE TITLE
second unreachable console switch hitbox inside of another switch on Toyota console model

### ISSUE THREAD

**Issue by J0riUnderscore** [CommandrMoose/TardisRefined#255]
### Issue description

flying the tardis while using the Toyota console model, at the time of the bug I was using the violet variant but looking at the switch hitboxes on other variants of Toyota shows the same placements and would assumedly result in similar issues. while in flight and having to do the switch mini game there was one unreachable switch that I could not press for the mini game. Turning on hit boxes with f3+b I saw the switch that I couldn't reach was inside of the GPS switch, I was able to mouse over it to see its icon but for some reason attempts to press it wouldn't work, keeping it in its critical state.

![2024-05-10_21 44 01](https://github.com/WhoCraft/TardisRefined/assets/162057787/242095b8-f82b-4b45-9ebe-9110b79fe4f8)
![2024-05-10_21 45 48](https://github.com/WhoCraft/TardisRefined/assets/162057787/b489d072-2b4b-4c3a-923e-fc2699bbb8b4)

### Steps to reproduce

1. get a tardis
2. change it to toyota model
3. press f3 and b together to observe the clipping switch hit-boxes
4. fly the tardis
5. when playing the mini game that requires the player to hit switches, when the bugged switch becomes one of the switches needed to be pressed, pressing the bugged switch won't do anything, and will progress to its critical state despite players attempted intervention.

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

fabric loader version 0.15.11-1.20.2

### Tardis Refined version

v2.0

### Other relevant versions

other mods installed at the time of the observed bug:
jei-1.20.2-fabric-16.0.0.2
Xaeros_Minimap_24.1.1_Fabric_1.20.2

**Comment by J0riUnderscore** [comment]
another note is that after this I tried flying with the crystalline console and the console kept sparking in the same area I was having problems with the original bug but looking at hit boxes couldn't find any hidden or broken switches on the console and every mini game switch was pressed.

**Comment by Jeryn99** [comment]
Hello, thanks for bringing this issue to our attention - we thought we fixed all the placements with our BlockBench Plugin but it seems some have fallen through the net
