### ISSUE TITLE
Immersive Portals stops teleportation in ARS Airlock area

### ISSUE THREAD

**Issue by DMCHiggens** [CommandrMoose/TardisRefined#257]
### Issue description

when the console finishes the terraforming process, there is an airlock door. going in this airlock door causes some steam to come from the ceiling, and then nothing happens. the only door that works is the one that brings me back out to the console room. watching a video on the mod, it seems like im supposed to be teleported to another room but this does not happen for me. 

### Steps to reproduce

terraform the tardis
enter the console room
go to the airlock door and wait. 

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader 0.15.11

### Tardis Refined version

v2.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/mytAseWv

**Comment by CommandrMoose** [comment]
Uninstall Immersive Portals, this is a known issue and will be resolved soon.

**Comment by DMCHiggens** [comment]
thank you!! 
i was about to do that because i noticed it wasnt doing anything, but i decided food was going to happen first.

**Comment by Jeryn99** [comment]
PR involved in repairs https://github.com/WhoCraft/TardisRefined/pull/246
