### ISSUE TITLE
Fabric server crashes on startup

### ISSUE THREAD

**Issue by SpectrumFATM** [CommandrMoose/TardisRefined#262]
### Issue description

After installing the newest version of the mod for fabric my server crashes immediately. Please find the crashlog in the pastebin below.

### Steps to reproduce

1. Install the mod in the server mod directory.
2. Run the server.

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

0.15.11

### Tardis Refined version

v2.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/yDTnehEj

**Comment by Jeryn99** [comment]
Where did you get this build? You’re experiencing something we fixed a week ago and can no longer reproduce

**Comment by SpectrumFATM** [comment]
I uploaded it from my modrinth instance directly.

**Comment by SpectrumFATM** [comment]
Ive reinstalled my entire mudpack and the issue has been resolved.

**Comment by Jeryn99** [comment]
I hope the mud pack gave you the health benefits you desired
