### ISSUE TITLE
ARS corridor airlock improper teleport function

### ISSUE THREAD

**Issue by thecatlover67** [CommandrMoose/TardisRefined#263]
### Issue description

When attempting to access the ARS corridors from a fresh Tardis (altered Tardis shells and interiors untested) the airlock requires specific placement in order to teleport between the console room and the corridor hub.

### Steps to reproduce

1. In a Tardis console room or ARS corridor hub, enter the airlock to transfer between rooms. (May require that the world at one point (even if it doesn't currently) has had Immersive Portals installed)
2. Wait for it to cycle once.
3. Here it should not teleport you, not in my testing.
4. In order to teleport properly, once it finishes cycling, remain in the airlock and stand near the door you entered from.
5. It should now (from my testing) cycle normally.

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader 0.15.11

### Tardis Refined version

v2.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

N/A

**Comment by Jeryn99** [comment]
So what you're indicating that worlds that have had IP installed previously lead to this funky teleporter nonsense?

**Comment by Jeryn99** [comment]
This MAY be fixed indirectly by https://github.com/WhoCraft/TardisRefined/pull/246

**Comment by 50ap5ud5** [comment]
Can reproduce this. Fixed by 0cdadb4643c80d6ad5b5be7d4f0cd107e61334ac. The teleporting logic needed to use the correct position update by sending movement packets.
