### ISSUE TITLE
Terraformer doesn't work (2.0)

### ISSUE THREAD

**Issue by Joshuabump** [CommandrMoose/TardisRefined#264]
### Issue description

made the terraformer structure in creative mode, tried to activate it, didn't work 
![2024-05-12_23 26 50](https://github.com/WhoCraft/TardisRefined/assets/24300971/cc003596-7cfe-4417-8414-aa01699249ba)

### Steps to reproduce

1. place Root Shell
2. open it with shears 
3. enter it and place terraformer structure 
4. activate with amethyst screwdriver

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader Version 0.15.11

### Tardis Refined version

v2.0

**Comment by dhi-holo** [comment]
Just making certain
The structure is made out of 8 base copper blocks, not waxed, and a redstone block under the terraformer, right?

**Comment by 50ap5ud5** [comment]
Have you tried to use the amethyst screwdriver on the terraformer when there are no other mods installed besides TARDIS Refined?

**Comment by Joshuabump** [comment]
> Just making certain The structure is made out of 8 base copper blocks, not waxed, and a redstone block under the terraformer, right?

ok I just checked the spot in the creative inventory I was grabbing the copper blocks from and... yeah it was waxed copper OOPS, thank you! sorry! difgjhndifgjhndfigjhn
