### ISSUE TITLE
TARDIS GRAVITY WELL FALL DAMAGE

### ISSUE THREAD

**Issue by IntellMove** [CommandrMoose/TardisRefined#265]
### Issue description

https://github.com/WhoCraft/TardisRefined/assets/94828376/7c26713b-06b5-4d0a-b496-cb53826152a4

I'm not sure if this issue consists with other gravity wells.

### Steps to reproduce

1. Enter default TARDIS gravity well towards EOH
2. Go down all the way to the floor
3. Brutal Death

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.15.11

### Tardis Refined version

v2.0

**Comment by Jeryn99** [comment]
Please look at existing issues before filing a issue. https://github.com/WhoCraft/TardisRefined/issues/254
