### ISSUE TITLE
Tardis Key Doorlock

### ISSUE THREAD

**Issue by LordRunner** [CommandrMoose/TardisRefined#268]
### Issue description

If you lock the Door from the outside and then get sucked into the tardis, because it is materilizing around you (for example if you call the tardis to a landingpad) you can`t open or unlock the Door from the inside

### Steps to reproduce

1. Lock the Door from the outside
2. take a landingpad and step on it
3. call the locked tardis to this landingpad
4. (if you have the upgrade) get sucked into the tardis
5. try to get out of the tardis

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader Version: 0.15.11

### Tardis Refined version

v2.0

**Comment by CommandrMoose** [comment]
You can unlock the TARDIS by shift right clicking the door or left clicking the door control.
