### ISSUE TITLE
Tardis currentLocation bug

### ISSUE THREAD

**Issue by perfectlynormalorgans** [CommandrMoose/TardisRefined#272]
### Issue description

for the sake of this being easy to understand, i'll start with a quick summary of current events, then go on to explain the bug, and then give any other relevant information.

the series of events goes like this:

- Created new profile on curseforge, minecraft version 1.20.2, fabric version 0.15.11
- added tardis refined mod 2.0 
- added a few other mods, removed those that caused compatibilitiy issues.
- playyed on the modpack for a few days on multiplayer, seemed to be functioning verry smoothly except for occasional crashes, which never ended up causing any actual harm
- eventually, while the tardis was parked in the nether, person a (me) previously had their spawn set in the tardis, but ended up having their spawn anchor destroyed. person a died, respawning them at the starter spawn in the overworld. person a requested person b (a person i was playing this modpack with) pilot the tardis back to spawn in the overworld, person b proceeded to check the gps, see current position as 0, 0, 0, input the destination coordinates, throttle up and releaste the handbrake, and the entire world crashed. when person a tried to join back to the world, upon the loading percentage reaching 100%, the entire session crashed and gave the crash message 
"The game crashed whilst exception ticking world
Error: java.lang.NullPointerException: Cannot invoke "whocraft.tardis_refined.common.tardis.TardisNavLocation.getPosition()" because "this.currentLocation" is null"
the world would not start up from that point on.

relevant information:

- other worlds would start up completely fine, even other worlds with tardises in them, but the original world would always crash upon reaching 100% loaded.
- a few other dev patches have been tried to solve the problem, the same crashes have been given.
- i have tried looking through some values in the world with nbtexplorer, no luck in finding the currentLocation value at all.

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric version 0.15.11

### Tardis Refined version

v2.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/XGxcF0iT

**Comment by Jeryn99** [comment]
```java.lang.NullPointerException: Cannot invoke "whocraft.tardis_refined.common.blockentity.console.GlobalConsoleBlockEntity.getControlEnttityList()" because "controllerConsole" is null```

Lmao, getControlEnttityList looks like a typo got through

Issue should be impossible though, as controlEntityList is always declared...
