### ISSUE TITLE
Interior door texture glitch when external shell is changed

### ISSUE THREAD

**Issue by trentoncorson** [CommandrMoose/TardisRefined#273]
### Issue description

When I changed the external shell of the TARDIS the interior door texture bugged out until I opened it. I had extra shells when doing this and I have not tested to see if it is because of extra shells or not
![2024-05-15_14 48 12](https://github.com/WhoCraft/TardisRefined/assets/68886995/74e0365a-c772-4646-9d1e-f329efcd71b4)

### Steps to reproduce

1. Start by unlocking the upgrade needed to change the external shell
2. then go to the desktop and select a different shell texture
3. save and apply the new texture
4. exit the desktop and look at the door

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader Version 0.15.11-1.20.2

### Tardis Refined version

v2.0

**Comment by CommandrMoose** [comment]
This is an extra shells issue, please report it on that issue report.

**Comment by Jeryn99** [comment]
Re-Opened issue, as it is caused by TR not always correctly updating the exterior - this will be validated before 2.0.1 release
