### ISSUE TITLE
T.A.R.D.I.S Interaction Bug (Permanently Broken Tardis)

### ISSUE THREAD

**Issue by RazorBl8de** [CommandrMoose/TardisRefined#274]
### Issue description

I was learning about how to control the tardis, and I used it a few times.
However when I landed it back to where I grew it, after I left the tardis it became un-interactable.

I thought I just let the door switch burn out, but I tried using shears on it to make sure (because it had the coral exterior so shears should've changed it to factory) and it didn't work.

I do not know it this bug will always happen when you do these things or not. It is most likely a random bug with a possability.
Sorry for the uncertainty, but this is the best I can do.

The mods I was using was sodium, lithium, nvidium, tardis refined all of 1.20.2.

### Steps to reproduce

1. I simply progressed like you should; I grew a tardis, I gave it power, and I set up the console like normal.

2. I then took it for 3-4 test flights before sending it back to the location that I grew it from.

3. Try right clicking the door switch when you land. For me, it made a sound and did nothing, but it made the door opening sound on left click as if it worked. (the door didn't actually open or close though).

4. I then left my tardis, and when I left, it was closed (even though I had manually opened it inside the tardis), and it couldn't be interacted with.

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric - 0.15.11

### Tardis Refined version

v2.0

### Other relevant versions

I took off all of my other mods that weren't fps increasers, but I don't think they had anything to do with this problem.

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

Game didn’t crash, just permanently broke my tardis.

**Comment by GameRZ55** [comment]
I have this exact problem aswell, not sure why

**Comment by RazorBl8de** [comment]
I figured it out; When you left click the door toggle, it "locks" the tardis door, but I didn't know I did that and I opened the door with my hand after I locked it
