### ISSUE TITLE
Tardis crash caused permanent tardis crashing

### ISSUE THREAD

**Issue by Lordnerdious** [CommandrMoose/TardisRefined#275]
### Issue description

I was flying on a server and crashed, and my tardis was damaged and exploding for hours. After a day it finally stopped exploding, but was still overheated. I also couldnt right click on buttons, but I could left click them. Using ice in creative mode didnt fix it. No one else on the server has had this problem when crashing their tardis.

### Steps to reproduce

Im not sure what caused it but the steps would be
Play on a server
Pull handbreak at full throttle
This is when the issue occurred

[2024-05-15-1.log.gz](https://github.com/WhoCraft/TardisRefined/files/15334174/2024-05-15-1.log.gz)

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.15.11

### Tardis Refined version

v2.0

**Comment by Lordnerdious** [comment]
The link in the steps to reproduce is the crash log

**Comment by Jeryn99** [comment]
Please test again on 2.0.2 and let us know

**Comment by Lordnerdious** [comment]
I believe it may have been fixed, but there’s a chance that it only happens occasionally and I haven’t had that issue in my new testing

**Comment by 50ap5ud5** [comment]
Thanks, we will close this issue for now. If you can reproduce it consistently, please reopen this issue. If the reproduction steps or modloader versions were changed please note that too.
