### ISSUE TITLE
Immersive Portals Issues

### ISSUE THREAD

**Issue by Jeryn99** [CommandrMoose/TardisRefined#278]
### Issue description

This issue will be created in order to document Immersive Portals problems so we can document them and rectify them

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Various

### Tardis Refined version

v2.0

**Comment by GFlyGames** [comment]
https://github.com/WhoCraft/TardisRefined/assets/114268808/aa2a8dbd-fa9b-4132-bfe6-9cceaf90c805

**Comment by ThatBlockyPenguin** [comment]
Hi, when launching the mod normally, it start up ok, but if I add ImmPtl, it crashes with this log:
[crash-2024-05-22_13.32.54-client.txt](https://github.com/WhoCraft/TardisRefined/files/15403292/crash-2024-05-22_13.32.54-client.txt)

**Comment by Jeryn99** [comment]
> Hi, when launching the mod normally, it start up ok, but if I add ImmPtl, it crashes with this log: [crash-2024-05-22_13.32.54-client.txt](https://github.com/WhoCraft/TardisRefined/files/15403292/crash-2024-05-22_13.32.54-client.txt)

This is because we ripped out what enables the support last minute, so the game doesn't register our custom portal but still tries to give it a renderer - we will have this fixed in upcoming versions as it's a 10 second fix

**Comment by funniman-exe** [comment]
> > Hi, when launching the mod normally, it start up ok, but if I add ImmPtl, it crashes with this log: [crash-2024-05-22_13.32.54-client.txt](https://github.com/WhoCraft/TardisRefined/files/15403292/crash-2024-05-22_13.32.54-client.txt)
> 
> This is because we ripped out what enables the support last minute, so the game doesn't register our custom portal but still tries to give it a renderer - we will have this fixed in upcoming versions as it's a 10 second fix

Are you guys ever gonna make this a working feature again? Perhaps in the next update?
