### ISSUE TITLE
Game refuses to boot with TARDIS Refined 2.0.1

### ISSUE THREAD

**Issue by TARDISSYT** [CommandrMoose/TardisRefined#279]
### Issue description

The game throws an error and boots me out to the launcher with TARDIS Refined installed.
![image](https://github.com/WhoCraft/TardisRefined/assets/170211485/cece036d-7d9f-47c1-a8fd-2f505418a07f)
Image of the crash in the Launcher

### Steps to reproduce

1. Create a new modpack with Fabric 1.20.2 on CurseForge
2. Install TARDIS Refined
3. Launch the game, it should crash

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader Version 0.15.11

### Tardis Refined version

v2.0

### Other relevant versions

Mods have been installed, but they don't affect the mod except for Immersive Portals 4.1.4

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/i4PvmMRd

**Comment by Jeryn99** [comment]
Remove Immersive Portals

**Comment by TARDISSYT** [comment]
aight, that may be why it worked just fine on NeoForge (it doesn't have immersive on there I think)

**Comment by N3XUSEXE** [comment]
I am aware this issue is closed, but I am having the same problem but I only have refined tardis and fabric api in the mods folder

**Comment by CommandrMoose** [comment]
Then create a new issue please

**Comment by CommandrMoose** [comment]
Then create a new issue please

**Comment by TARDISSYT** [comment]
^
