### ISSUE TITLE
Issues with Extra Shells, Tardis Refined, Fabric and JEI

### ISSUE THREAD

**Issue by Thedarkladdy123** [CommandrMoose/TardisRefined#280]
### Issue description

Okay, any time i open the game with extra shells, it crashes but if i remove it, the game loads without the other mods enabled meaning the mods are installed and i haven't changed a thing besides removing extra shells but it loads as if none of the mods are installed.

### Steps to reproduce

Install Extra Shells, Fabric API, Tardis Refined, JEI. Then load up game. After game crashes remove ONLY extra shells. Load game and open world

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader 0.15.11

### Tardis Refined version

v2.0

### Other relevant versions

Extra Shells Ver: 1.0.2
Jei 1.20.2 version 16.0.0.2
Fabric API 1.20.2 0.91.6+

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/T4drSt6B

**Comment by Jeryn99** [comment]
It helps if you also install TARDIS Refined aswell...

**Comment by Thedarkladdy123** [comment]
> It helps if you also install TARDIS Refined aswell...

 do have it installed

**Comment by Jeryn99** [comment]
your log says you do not

**Comment by Jeryn99** [comment]
As you can see, it does not appear in the list on your log

```
Fabric Mods: 
		extra_shells: extra_shells 1.20.2-1.0.2
		fabric-api: Fabric API 0.91.6+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.43+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.6+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.11+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.70+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.28+c8b10480a0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.56+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.5+f4be560ba0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.14+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.12+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.11+239dafd8a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.47+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.13+4944b5a5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 16.0.0.2
		minecraft: Minecraft 1.20.2```

**Comment by Thedarkladdy123** [comment]
> As you can see, it does not appear in the list on your log
> 
> ```
> Fabric Mods: 
> 		extra_shells: extra_shells 1.20.2-1.0.2
> 		fabric-api: Fabric API 0.91.6+1.20.2
> 			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
> 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.43+b1792f7da0
> 			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
> 			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
> 			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
> 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
> 			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
> 			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
> 			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
> 			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
> 			fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b3a0
> 			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.6+b1792f7da0
> 			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
> 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
> 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.11+b1792f7da0
> 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
> 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
> 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
> 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.70+df3654b3a0
> 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
> 			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
> 			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
> 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
> 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
> 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.28+c8b10480a0
> 			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
> 			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
> 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.56+f4b7e424a0
> 			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
> 			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
> 			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.5+f4be560ba0
> 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
> 			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
> 			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.14+52b3ebe5a0
> 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.12+b1792f7da0
> 			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
> 			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
> 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
> 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
> 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
> 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
> 			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
> 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.11+239dafd8a0
> 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
> 			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
> 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.47+b1792f7da0
> 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
> 			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.13+4944b5a5a0
> 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
> 		fabricloader: Fabric Loader 0.15.11
> 			mixinextras: MixinExtras 0.3.5
> 		java: OpenJDK 64-Bit Server VM 17
> 		jei: Just Enough Items 16.0.0.2
> 		minecraft: Minecraft 1.20.2```
> ```

![image_2024-05-19_190404906](https://github.com/WhoCraft/TardisRefined/assets/71188383/cadc90ac-39e4-479e-8ad4-d3f3f5986700)

[crash-2024-05-19_19.03.34-client.txt](https://github.com/WhoCraft/TardisRefined/files/15371059/crash-2024-05-19_19.03.34-client.txt)
 i had it installed and it's still the same crash

**Comment by CommandrMoose** [comment]
The game doesn't think so.

Can you try installing the mods in the root mod folder? Not under mods/mods/mods/mods/mods

**Comment by Jeryn99** [comment]
£10 bet that you've installed the NeoForge version lol

**Comment by Thedarkladdy123** [comment]
![image](https://github.com/WhoCraft/TardisRefined/assets/71188383/15ad0dff-6797-4956-858a-54490ab2955d)
nope. fabric

**Comment by Jeryn99** [comment]
You realize that currently they have the same filename?

**Comment by Jeryn99** [comment]
And you have two Tardis refined jars in there now?

**Comment by CommandrMoose** [comment]
Please try the following in order to resolve this:

1. Download the correct version of TARDIS Refined and Extra Shells for Fabric.
2. Run your mods under .minecraft/mods and not  .minecraft/mods/mods/mods/mods.

We are closing this issue as this is a user error.
