### ISSUE TITLE
Mod doesn’t exist

### ISSUE THREAD

**Issue by Ember808** [CommandrMoose/TardisRefined#282]
### Issue description

When I’ve tried loading the mod the game says there is no mod and nothing for it exists, it’s in the mods folder the game just doesn’t recognize it

### Steps to reproduce

Load up the game normally

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Latest version

### Tardis Refined version

v2.0

### Other relevant versions

I use Litmatica, essential mod, and some fps mods and I’m not sure what f they are involved

**Comment by CommandrMoose** [comment]
Please ensure you've downloaded the correct jar file - for Fabric.
