### ISSUE TITLE
immersive portals crashes the game

### ISSUE THREAD

**Issue by goddammn** [CommandrMoose/TardisRefined#284]
### Issue description

when installed the tardis refined and immersive portals, it instantly crashes

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric - 0.15.11

### Tardis Refined version

v2.0

**Comment by Jeryn99** [comment]
https://github.com/WhoCraft/TardisRefined/issues/278#issuecomment-2124689789
