### ISSUE TITLE
Roots cover entrance to root shell?

### ISSUE THREAD

**Issue by LouC1901** [CommandrMoose/TardisRefined#288]
### Issue description

After growing root plant or placing root shell, the entrance is inaccessible. Message pops up as 'covered with roots'. Am I missing something or is this a bug? 

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

0.15.11

### Tardis Refined version

v2.0

**Comment by CommandrMoose** [comment]
https://wiki.tardisrefined.net/getting-started.html

Please ensure you've read the wiki before reporting issues.
