### ISSUE TITLE
Game failing to boot with TARDIS mod

### ISSUE THREAD

**Issue by N3XUSEXE** [CommandrMoose/TardisRefined#290]
### Issue description

This issue has already been reported, but the circumstance of it happening to me are different, along with the error code. The last person to report this simply had to remove the immersive portals mod from the folder. I do not have it in the folder but it still refuses to work, please help. 

![image_2024-05-28_164728337](https://github.com/WhoCraft/TardisRefined/assets/152349434/dd9a2ad7-8132-4ddf-b0da-75f39a438320)

### Steps to reproduce

1. Use default launcher
2. Switch to fabric loader 1.20.2
3. Add TARDIS mod and fabric API to mods folder
4. Attempt to start the game, it crashes

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader Version 0.14.24

### Tardis Refined version

v2.0

**Comment by CommandrMoose** [comment]
Please attach the crash log, we need more information.

**Comment by TARDISSYT** [comment]
If you happen to not know where the crash logs are: go to your Minecraft instance, open the folder called "crash-reports" and get the latest one. put it in Pastebin or something and put the link in :P

**Comment by funniman-exe** [comment]
Getting the same error, but i have the crash log. Here it is:
[crash-2024-05-28_16.09.29-client.txt](https://github.com/WhoCraft/TardisRefined/files/15476812/crash-2024-05-28_16.09.29-client.txt)

**Comment by Jeryn99** [comment]
```Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mtr.mixins.json:UnknownPacketMixin from mod mtr] from phase [DEFAULT] in config [mtr.mixins.json] FAILED during APPLY```


Do you have this mod installed? https://www.curseforge.com/minecraft/mc-mods/minecraft-transit-railway

**Comment by funniman-exe** [comment]
> `Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mtr.mixins.json:UnknownPacketMixin from mod mtr] from phase [DEFAULT] in config [mtr.mixins.json] FAILED during APPLY`
> 
> Do you have this mod installed? https://www.curseforge.com/minecraft/mc-mods/minecraft-transit-railway

Yes I do, it's kinda an important part of the server I plan to run this on.
I'm hoping there's a way I can fix this without removing MTR.

**Comment by Jeryn99** [comment]
Cool, they need to fix whatever it is their doing to our packets
