### ISSUE TITLE
Tardis Flight Loop sound only sometimes plays

### ISSUE THREAD

**Issue by funniman-exe** [CommandrMoose/TardisRefined#293]
### Issue description

I've seen in YouTube showcases of this mod that when the Tardis is Traveling it plays an ambiance similar to the sound for taking off and landing but looped. However, in my and other Tardis's on my server, this ambiance doesn't always play. I've only actually heard it play twice, and I've flown my Tardis a lot.

### Steps to reproduce

1. Aquire Tardis
2. Get in Tardis
3. Engage the throttle
4. Wait for the takeoff sound to finish
5. Issue occurs

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader v0.15.11

### Tardis Refined version

v2.0

**Comment by Jeryn99** [comment]
We've been looking into it
