### ISSUE TITLE
Tardis door, console, and bulkhead doors cloned.

### ISSUE THREAD

**Issue by NateslPlayzzz** [CommandrMoose/TardisRefined#298]
### Issue description

When i changed the desktop in version 2.02, it cloned the tardis doors, console, and bulkhead doors.

![2024-06-02_19 15 09](https://github.com/WhoCraft/TardisRefined/assets/69865617/f92b311a-5a2c-42ff-be1a-578b5196ac97)
![2024-06-02_19 15 12](https://github.com/WhoCraft/TardisRefined/assets/69865617/70dea4e3-37ef-4187-bf83-bf89a0664a5c)

### Steps to reproduce

1. Create Tardis
2. Change desktop (any will work)
3. Door, Console, and bulkhead doors will end up cloned.

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.15.10

### Tardis Refined version

v2.0.2

### Other relevant versions

Could be Immersive Portals. Thats the ONLY other mod i have on.

**Comment by NateslPlayzzz** [comment]
After roughly 10-15 mins they have seemed to have disappeared. Unsure if these were ghost entities or not.

**Comment by J0riUnderscore** [comment]
I've had this too with pretty much the same version of the mod and immersive portals, found that this can also happen by leaving the console room through the corridor airlock and going back into the console room through the airlock. when I did this entity clones of the models (front door, console, airlock door) would render overlapping the real ones. you can see this when the airlock doors open, the clones' doors stay closed allowing you to appear to walk through the closed doors, the front door model will render the closed door model over the doors even when you open the doors. these clones will also remain when you change desktops too.

**Comment by Jeryn99** [comment]
It's immersive portals being Immersive Portals
