### ISSUE TITLE
terraformed tardis locked off

### ISSUE THREAD

**Issue by The11thDoctorWho** [CommandrMoose/TardisRefined#299]
### Issue description

I can't shear the roots off after the tardis is terraformed

### Steps to reproduce

grow tardis
shear the roots
terraform it
wait
attempt to shear roots again and fail

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.2.32

### Tardis Refined version

v2.0.2

**Comment by GameRZ55** [comment]
i am experiencing this aswell!!

**Comment by J0riUnderscore** [comment]
same problem in the fabric 1.20.1 version

**Comment by CommandrMoose** [comment]
Thanks for reaching out guys. We've released a fix for this issue which can be found right now on Modrinth. Please let me know how you go, as you will need to create a new TARDIS to resolve this issue.

https://modrinth.com/mod/tardis-refined/versions
