### ISSUE TITLE
Massive FPS drop when enabled

### ISSUE THREAD

**Issue by Hot-M3ss** [CommandrMoose/TardisRefined#300]
### Issue description

The FPS for the pack I'm building tanks to 20fps from a solid 60 (I have this capped at 60 so it may be higher) and causes my computer to sound like a rocket when it normally doesn't.

### Steps to reproduce

1. Enable the mod, max frames drop to 20fps.
2. Disable the mod, max frames goes up to 60fps.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.2.32

### Tardis Refined version

v2.0.2

### Other relevant versions

[latest.log](https://github.com/user-attachments/files/15536242/latest.log)
Curseforge Modpack:
[ISSUE-FPS.zip](https://github.com/user-attachments/files/15536275/ISSUE-FPS.zip)

**Comment by Bonkjumper** [comment]
Good day, I seem to have an issue similar to this, could you possibly tell me the cause of the problem so I can attempt fixing it myself?

**Comment by Hot-M3ss** [comment]
> Good day, I seem to have an issue similar to this, could you possibly tell me the cause of the problem so I can attempt fixing it myself?

I am unsure, I am reopening the issue so the team is aware, my computer is beefy so this is a shocking issue.

**Comment by Hot-M3ss** [comment]
![image](https://github.com/WhoCraft/TardisRefined/assets/71112588/1fca4c12-b25e-4e14-8cf0-e2fb4f68d8e5)
Its 78% of the render thread? No tardises are spawned in this world.

**Comment by Jeryn99** [comment]
Man I love Forge - thanks for these stats, strange that the overlay runs this high

But thinking about it, it does somewhat make sense because the games constantly checking if the players in a gravity well


Leave this with me, I'll investigate

**Comment by Jeryn99** [comment]
Fixed
