### ISSUE TITLE
Can't travel

### ISSUE THREAD

**Issue by Opalo56138** [CommandrMoose/TardisRefined#304]
### Issue description

Everytime I travel it starts at the world spawn. My initial starting point would be 6,000 blocks away but no matter where I want to travel too it would bring me to world spawn which would make my travel take longer and not bring me to the right place. When I would run out of fuel and stop my Tardis I can walk out and see on my minimap that I am even farther from where I want to go because no matter what I do I just start at world spawn. I already have the Waypoints upgrade, that doesn't help either. Would like a fix on this asap because at this point the Tardis' are unusable. Using the 1.20.1 version.

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

Modrinth

### Tardis Refined version

v2.0.1

**Comment by Opalo56138** [comment]
Even after updating to the latest version (because I did not see that it was updated a day ago) the problem still persists.

**Comment by 50ap5ud5** [comment]
Can you reproduce this on mod version 2.0.2 for Minecraft 1.20.2? When testing please make sure no other mods besides Tardis Refined are installed. This helps to reduce the possibility of other mods interfering with the Tardis.

**Comment by Opalo56138** [comment]
I'm not sure. I've only used the 1.20.1 fabric version on Modrinth. It's
for the server I have with friends. My other friend also has this problem
over and over. I'll send a video of what happens. It's simple but it's to
help with understanding and showing the process.

**Comment by Opalo56138** [comment]
Here's the link to the video. https://youtu.be/89J4EUJBYHw
Shows the my whole process.

**Comment by Opalo56138** [comment]
Was there any update to this?

**Comment by Jeryn99** [comment]
is the issue present in 2.0.5?

**Comment by Jeryn99** [comment]
Presuming resolved, please comment if the issue continues
