### ISSUE TITLE
falling block crash

### ISSUE THREAD

**Issue by seremo04** [CommandrMoose/TardisRefined#305]
### Issue description

my game keeps crashing anytime sand or gravel or blocks in that sort s tarts falling. 

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

[NEOFORGE] TARDIS Refined 1.20.2-2.0.2

### Tardis Refined version

v2.0.2

**Comment by CommandrMoose** [comment]
We cannot help you without a crash report.
