### ISSUE TITLE
Game crashes upon attempting to land the TARDIS in a void dimension

### ISSUE THREAD

**Issue by nanowuu** [CommandrMoose/TardisRefined#309]
### Issue description

When trying to finish flight and land in a dimension where there are no solid blocks in the column (in this case Ad Astra's "Orbit" dimension) the game crashes. This is probably because findValidLocationInColumn calls itself with an offset BlockPos but can't find one in such a dimension

### Steps to reproduce

Try to land the TARDIS in a dimension with only void

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader 0.15.11

### Tardis Refined version

v2.0.2

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://gist.github.com/nanuwo/f695ef7b6c20c5b028d372072243e02d

**Comment by Hot-M3ss** [comment]
This also happens when going to the Aether, which has blocks.
[crash-2024-06-08_11.14.27-server.txt](https://github.com/user-attachments/files/15748608/crash-2024-06-08_11.14.27-server.txt)

**Comment by 50ap5ud5** [comment]
Thanks, this will be looked into in future versions

**Comment by Hot-M3ss** [comment]
> This also happens when going to the Aether, which has blocks. [crash-2024-06-08_11.14.27-server.txt](https://github.com/user-attachments/files/15748608/crash-2024-06-08_11.14.27-server.txt)

To clarify I am running forge.

**Comment by NovaAstral** [comment]
This happens in ad astra orbit dimensions on forge aswell
