### ISSUE TITLE
Not an issue, but I need help with immersive portals

### ISSUE THREAD

**Issue by TheEpicTen** [CommandrMoose/TardisRefined#310]
### Issue description

Hello. Sorry for adding this as an issue, it’s not, but it seems to be the best way for me to contact people who know about this mod. How can I get it to work with Immersive Portals? I don’t understand the thing in the Readme, and I don’t have experience with gradle, so could someone tell me how I can get it to work if it doesn’t by default (not downloaded mod yet, so I’ll close the issue if it works by default when I try the mod)? Thanks.

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

N/A

### Tardis Refined version

v2.0.1

### Other relevant versions

Immersive Portals

**Comment by Jeryn99** [comment]
Matters like this should be taken to the Discord.


You simply install Immersive Portals and Tardis Refined together on Fabric

**Comment by TheEpicTen** [comment]
I don’t use Discord, but thanks.
