### ISSUE TITLE
Not sure if this counts as an issue, but I need some help none the less.

### ISSUE THREAD

**Issue by Sombody-New** [CommandrMoose/TardisRefined#311]
### Issue description

I had redownloaded the updated version of the mod today, and I also have immersive portals mod. The immersive portals mod doesn't seem to be working for me though with the Tardis. It works for everything else. Can someone help me please?

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

0.15.11

### Tardis Refined version

v2.0.2

### Other relevant versions

v1.20.2-2.0.3  Is what I downloaded from curseforge.

**Comment by Hot-M3ss** [comment]
Its disabled by default due to some issues, but can be enabled in the config if I recall correctly. (I AM NOT A MOD/DEV, I am providing information from memory and it may not be 100% accurate.)

**Comment by Sombody-New** [comment]
Config as in like, a file? Or in-game. If it's in-game i can't find that anywhere....

**Comment by 50ap5ud5** [comment]
Can you please elaborate on what you define as "not working"? E.g. Cannot view interior from exterior shell.

**Comment by Sombody-New** [comment]
Yes, that AND I can't see outside from within the interior as well. I don't know how to get it to work...

**Comment by Jeryn99** [comment]
Considered Fixed
