### ISSUE TITLE
Console stops rendering if you look up

### ISSUE THREAD

**Issue by NovaAstral** [CommandrMoose/TardisRefined#312]
### Issue description

Looking up too far while next to the console makes it stop rendering.

### Steps to reproduce

Stand infront of the console and look up.

### Minecraft version

1.20.1

### Mod Loader Platform type

Neoforge

### Mod Loader version

NeoForge v47.1.106

### Tardis Refined version

v2.0.3

### Other relevant versions

Tardis Refined is on 2.0.3, but there's no 2.0.3 option in the template.

**Comment by NovaAstral** [comment]
This also happens to everything with a custom model (and the astral manipulator effect), if the base block is offscreen, the entire model stops rendering.

**Comment by Jeryn99** [comment]
Man I love Forge being Forge

**Comment by Jeryn99** [comment]
Fixed
