### ISSUE TITLE
Can't travel to larger number coordinates

### ISSUE THREAD

**Issue by RavnixVioletBlueFlame** [CommandrMoose/TardisRefined#314]
### Issue description

Trying to travel specifically to larger number coordinates, either in the overworld or the nether (or other variant) results in either not moving at all, or only moving to a location similar to the last with barely any noticeable difference in distance traveled. Always resulting in absorbing all fuel. The same seems to happen with summoning the tardis even when it begins with full fuel.

### Steps to reproduce

Enter coordinates with more than three digits (four digits or more) either normal or "negative" (example 93012, 67, -9840). Tardis travels for a long period. Never reaching intended destination.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.2.20

### Tardis Refined version

v2.0.3

### Other relevant versions

All the Mods 9 modpack, and cobblemon

**Comment by Jeryn99** [comment]
Is this still a issue in 2.0.5?

**Comment by RavnixVioletBlueFlame** [comment]
> Is this still a issue in 2.0.5?

I think it's much better than before! The percentages raise up faster once it's upgraded with speed buffs. Though maybe a little more speed wouldn't be a bad idea? But I can at least travel places now or move more than merely a few feet away!

**Comment by Jeryn99** [comment]
Speed Upgrades were added, this is now repaired
