### ISSUE TITLE
Can't see eye of harmony

### ISSUE THREAD

**Issue by RavnixVioletBlueFlame** [CommandrMoose/TardisRefined#315]
### Issue description

Activating power doesn't result in being able to see the Eye Of Harmony, though power still activates regardless.

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.2.20

### Tardis Refined version

v2.0.3

### Other relevant versions

All the mods 9, cobblemon

**Comment by Jeryn99** [comment]
Image please

**Comment by SelynCatto** [comment]
all the mods 9 features embeddium extras and has block entity culling, you need to turn that off or extend the range

**Comment by RavnixVioletBlueFlame** [comment]
> all the mods 9 features embeddium extras and has block entity culling, you need to turn that off or extend the range

No idea how to do that. I tried looking for it in settings but failed to find any kind of config for it.. It runs on a server so idk how limited that makes it.

**Comment by RavnixVioletBlueFlame** [comment]
> Image please

![2024-07-30_09 09 37](https://github.com/user-attachments/assets/07dd0e65-dd85-4162-80a5-4ca05ac6def9)
