### ISSUE TITLE
Unable to change or destroy the console unit outside the TARDIS

### ISSUE THREAD

**Issue by HikariYlan** [CommandrMoose/TardisRefined#316]
### Issue description

I misplaced my console unit in my survival world, and when a team member on Discord told me to use the console configurator, it didn't work. And I did placed the console configurator in the right way. I tried in creative mode too and it also didn't work. The pattern manipulator works however.
I don't have any other mods, just this one.

### Steps to reproduce

1. Load a new world in creative
2. Place a console unit and a console configurator
3. Try to change the console unit, or to destroy it
4. You can grow a TARDIS and see that it works in it, even if the console is not turned on

https://github.com/WhoCraft/TardisRefined/assets/90347779/6fcab373-c18d-48f2-8bed-5ba5be2f01d9

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 42.7.17

### Tardis Refined version

v2.0.3

**Comment by DaPuffer** [comment]
Having the same issue in 2.0.7.
