### ISSUE TITLE
Questcraft tardis refined crash

### ISSUE THREAD

**Issue by camro3892** [CommandrMoose/TardisRefined#317]
### Issue description

everytime i add tardis refined to any version of questcraft it locks me out of the instance meaning it crashes everytime i open that instance

### Steps to reproduce

create an instance of questcraft add tardis refined then click update instance.

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

fabric

### Tardis Refined version

v2.0.3

### Other relevant versions

1.20.2 till 1.19,2

**Comment by Jeryn99** [comment]
![image](https://github.com/WhoCraft/TardisRefined/assets/36424503/527ac6e4-be0b-45e3-a69c-109d04ebd07d)

**Comment by camro3892** [comment]
i am not able to extract the logs due to the quest not having that ability due to update 63

**Comment by Jeryn99** [comment]
Your game creates logs, if a mod is stopping your game creating latest.log you should consider uninstalling it as that is incredibly invasive

**Comment by camro3892** [comment]
i am not able to access any sort of file management on the quest

**Comment by Jeryn99** [comment]
Oh I see, you are running the game directly on your QuesT?

**Comment by camro3892** [comment]
yes
mind adding my discord?

**Comment by Jeryn99** [comment]
We do not support running on devices not officially intended to be run on by Mojang. If you can re-create the crash in a support environment we will look into it.

**Comment by camro3892** [comment]
ok
