### ISSUE TITLE
Tardis Does not Travel if multipl players are inside

### ISSUE THREAD

**Issue by juke31123** [CommandrMoose/TardisRefined#321]
### Issue description

When me and my friend try to travel via the tardis is just does not work!

### Steps to reproduce

no idea what causes it and how to reporduce it

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

forge 47.2.0

### Tardis Refined version

v2.0.3

**Comment by Jeryn99** [comment]
Do you have fuel? Have you set up the eye of harmony?

**Comment by juke31123** [comment]
yes i can travel alone just not when my friend is by my side
