### ISSUE TITLE
Game Crash When Using Scissors on Root Shell with Both Valkyrien Skies and TARDIS Refined Installed

### ISSUE THREAD

**Issue by Dithree** [CommandrMoose/TardisRefined#324]
### Issue description

As mentioned in the title, using scissors to right-click on the Root Shell after creating the TARDIS with both Valkyrien Skies and TARDIS Refined installed causes the game to crash.
However, I'm not sure if an issue involving multiple mods should be posted here. I apologize if this is the wrong place to report it.

### Steps to reproduce

1.Install Valkyrien Skies and TARDIS Refined
2.Place a Root Shell
3.Use scissors to right-click on the Root Shell
4.Game crashes

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

fabric loader 0.15.11-1.20.1

### Tardis Refined version

v2.0.3

### Other relevant versions

[Fabric 1.20.1] valkyrienskies-120-2.3.0-beta.5

**Comment by Jeryn99** [comment]
So uh, where’s the crash report so we can diagnose?

**Comment by Dithree** [comment]
> So uh, where’s the crash report so we can diagnose?

Sorry, I forgot to upload the file.

[crash-2024-06-28_20.34.22-server.txt](https://github.com/user-attachments/files/16029742/crash-2024-06-28_20.34.22-server.txt)

**Comment by Jeryn99** [comment]
This is something you will need to bring to them, there's nothing directly referring to Tardis Refined within the crash report. Please make a issue on their Github and then link it here so we can stay in the loop on this issue

**Comment by Dithree** [comment]
> This is something you will need to bring to them, there's nothing directly referring to Tardis Refined within the crash report. Please make a issue on their Github and then link it here so we can stay in the loop on this issue

Thank you for your response. Here is another Github link.
However, it seems to indicate that it will not be compatible, which is unfortunate.
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/885

**Comment by kotx** [comment]
Yes
