### ISSUE TITLE
pattern datapacks possibly broken

### ISSUE THREAD

**Issue by J0riUnderscore** [CommandrMoose/TardisRefined#328]
### Issue description

I'm still not 100% sure but I've tried everything and it's just not working
I've been trying to make patterns work on a datapack and it's not been working. I've copied and pasted the code from the wiki example, only replacing the names and ids for my datapack and it doesn't work. I've downloaded an already working datapack for an older tardis refined (since older desktop datapacks still work with newer mod versions I thought there couldn't be too much of a difference) and it didn't work. I scanned through the code of this older datapack and the only difference I could find was a singular line of code that said ","replace": false" just after the last square bracket so I coped and pasted it in this datapacks code in the same spot just after the last square bracket and it still just doesn't work.

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

fabric-api-0.92.2+1.20.1

### Tardis Refined version

v2.0.4

**Comment by Jeryn99** [comment]
Upload your attempt

**Comment by J0riUnderscore** [comment]
[testpatterns.zip](https://github.com/user-attachments/files/16058576/testpatterns.zip)
[test_patterns.zip](https://github.com/user-attachments/files/16058577/test_patterns.zip)

the one with the underscore is the resource pack and the one without is the data pack
