### ISSUE TITLE
Astral manipulator not crafting?

### ISSUE THREAD

**Issue by Nagakiller3** [CommandrMoose/TardisRefined#333]
### Issue description

Hi, I just added this mod to BCG Plus using curseforge and the astral manipulator does not seem to work does anyone know anything about it/ how to fix it?
I restarted the game/world and moved to different locations, it still makes a noise but it's the same noise it makes when it fails/does not craft.

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.15.11

### Tardis Refined version

v2.0.4

**Comment by Jeryn99** [comment]
Had a look, this is caused by the diagonal walls mod.
