### ISSUE TITLE
Lost TARDIS in another dimension while handbraked, now I can't find it.

### ISSUE THREAD

**Issue by Sniff-Boy** [CommandrMoose/TardisRefined#336]
### Issue description

I was in the dimensional doors limbo dimension and tried to leave via tardis but while in flight i thought it would take too long and i didnt have enough fuel so i ended up forgetting how to safely land and stuck on the handbrake, exploded a little bit and left the tardis to go find my own way out, but once i did i couldnt call it back to me with a landing pad since it was handbraked, but i also cant go and find it either. what should i do to get it back? also sorry for long description im not that good at shortening things.

### Steps to reproduce

1. be in any dimension with tardis
2. activate handbrake
3. leave dimension the normal way, leaving the tardis in the dimension
4. forget where you left the tardis

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge - 47.3.0

### Tardis Refined version

v2.0.3

**Comment by SelynCatto** [comment]
If you lose the physical TARDIS and have it handbraked, you can't get it back unless an admin (or you with commands) teleports you in via the /tardis_refined interior command

**Comment by Jeryn99** [comment]
User error, community member has offered solution
