### ISSUE TITLE
Whenever I exit the TARDIS, I end up teleporting in a random area.

### ISSUE THREAD

**Issue by BlueBox2605** [CommandrMoose/TardisRefined#338]
### Issue description

When I leave the TARDIS, I am teleported to random area of the overworld, where I am lost, this issue seems to happens after a world has been created after a few days, meaning this has happened multiple times on serval worlds, I don't know why or how, I hope the information has been useful and the issue resolved.

### Steps to reproduce

I am unaware of what the steps are to this issue.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge Version 47.2.32

### Tardis Refined version

v2.0.3

### Other relevant versions

No other versions relevant.

**Comment by BlueBox2605** [comment]
I am checking my previous worlds with TARDIS's and each one has the same issue now

**Comment by BlueBox2605** [comment]
I am checking my previous worlds with TARDIS's and each one has the same issue now, I hope this issue resolved very soon.

**Comment by Jeryn99** [comment]
Have you tried with 2.0.5?

**Comment by Dromnil** [comment]
I can attempt to see if this is still an issue, but I will say that the most recent version as of a month ago was simply crashing the game upon creating a TARDIS.

**Comment by thankfuldeadman** [comment]
Yeah, I've been having this problem with the backrooms mod not sure if it was the mod or Tardis refined.

**Comment by Jeryn99** [comment]
Hello all, (@Dromnil , @thankfuldeadman, @BlueBox2605)
Do you happen to know if the "random area" happens to have the coordinates 0,0,0?

**Comment by Jeryn99** [comment]
I'm going to consider this stale, if the issue is still present please leave a comment
