### ISSUE TITLE
Bed explodes when right-clicking inside the tardis

### ISSUE THREAD

**Issue by Kueriost** [CommandrMoose/TardisRefined#339]
### Issue description

When right-clicking the bed, it explodes. 

### Steps to reproduce

Place bed and right-click to sleep.

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

sodium fabric mc 1.20.2 0.5.5

### Tardis Refined version

v2.0.4

**Comment by Jeryn99** [comment]
https://github.com/WhoCraft/TardisRefined/issues/198

Please see this issue

**Comment by Kueriost** [comment]
thank you. Apologise for another of the same thread. For datapacks, do I just drag and drop to a specific folder?

**Comment by Jeryn99** [comment]
> thank you. Apologise for another of the same thread. For datapacks, do I just drag and drop to a specific folder?

https://minecraft.fandom.com/wiki/Tutorials/Installing_a_data_pack

**Comment by Kueriost** [comment]
thank you.
