### ISSUE TITLE
 If the Tirdis's flight was somehow interrupted, she teleports as if she were flying from zero coordinates

### ISSUE THREAD

**Issue by Jaitar** [CommandrMoose/TardisRefined#341]
### Issue description

If I start flying onto the TARDIS, for example, from “1500 ~ 1000” coordinates to “2800 ~ 2000” coordinates and press the handbrake or run out of fuel 10% of the way, then I will end up not at “1630 ~ 1100” coordinates but at “130 ~ 100” 
(use google translator)

Original: 
Если я начну лететь на TARDIS к примеру с "1500 ~ 1000" координат на "2800 ~ 2000" координаты и нажму ручной тормоз или закончится топливо на 10% пути, то я окажусь не на "1630 ~ 1100" координатах а на "130 ~ 100"

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

forgeVersion 47.3.1

### Tardis Refined version

v2.0.4

**Comment by Jeryn99** [comment]
Since been fixed
