### ISSUE TITLE
Cant Craft Artron Pillars Using The Astral Manipulator In The Eye Of Harmony

### ISSUE THREAD

**Issue by OllyWHO01** [CommandrMoose/TardisRefined#343]
### Issue description

I cant create the arton pillers after placing the blocks and sonicing them. I know the astral manipulator works because I've used it for the console and terraformer.

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

Most Recent 

### Tardis Refined version

v2.0.4

**Comment by Jeryn99** [comment]
Do you have Diagonal walls / fences installed?

**Comment by OllyWHO01** [comment]
> Do you have Diagonal walls / fences installed?

Yes I do

**Comment by Jeryn99** [comment]
https://github.com/Fuzss/diagonalwalls/issues/8
