### ISSUE TITLE
Distant horizons incompatability

### ISSUE THREAD

**Issue by Dromnil** [CommandrMoose/TardisRefined#345]
### Issue description

Because of how the TARDIS dimension is coded in some way, it overwrites overworld chunks with the Distant Horizions mod, which uses previously loaded chunks to show you far off unloaded regions. I have had this issue with other dimension mods, but unless the dimension is coded to take place in a different location than the overworld chunks, it rewrites the LOD chunks in memory and makes it look as though the TARDIS chunks are in the overworld. Basically, it does this when I leave the tardis and go to the coordinates it had loaded in:
![image](https://github.com/user-attachments/assets/b5ac74ae-9a03-41b0-800d-790f943d531c)

### Steps to reproduce

1. Download distant horizons
2. Explore overworld chunks
3. Enter a tardis and explore the same coordinates
4. return to the overworld and go to those same coordinates one more time.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.3.0

### Tardis Refined version

v2.0.3

**Comment by Jeryn99** [comment]
Compatibility issue that's beyond our scope from a mod that alters the rendering engine.
