### ISSUE TITLE
Beds Explode

### ISSUE THREAD

**Issue by IvanDPhantom** [CommandrMoose/TardisRefined#347]
### Issue description

So not really a bug but more like a request to add a feature, because please let us sleep in the TARDIS, we could in the 1.19.2, why not here?

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 43.1.43

### Tardis Refined version

v2.0.4

### Other relevant versions

In any other case, Il ike this mod

**Comment by Jeryn99** [comment]
It was a oversight in 1.19.2 - you were not supposed to be able to

This will not be added as a feature, but this can be enabled via a datapack which can be found in the Discord
