### ISSUE TITLE
Redstone link from "Create" ineffective inside Tardis dimension

### ISSUE THREAD

**Issue by unknowObject** [CommandrMoose/TardisRefined#349]
### Issue description

Inside the Tardis dimension, a component from mod "Create" called "Redstone link" which allows you to send and receive redstone signal wireless is not working.
![hongshi (2)](https://github.com/user-attachments/assets/e528ed36-491d-47c1-b017-bf536f1cab7c)

### Steps to reproduce

1. Install mod: Tardis-refined and Create.
2. Place redston link from Create inside Tardis and set them to the same frequncy https://create.fandom.com/wiki/Redstone_Additions#Redstone_Link)
3. Input a redstone signal to the redstone link that send signals.
<img width="646" alt="image" src="https://github.com/user-attachments/assets/3e9534da-07d4-4a97-ab78-1643b748799c">

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge Version 47.3.5

### Tardis Refined version

v2.0.4

### Other relevant versions

The Tardis Refined mod is actually using mod version 2.0.5 which doesn't appeared as a option in last section.

**Comment by TARDISSYT** [comment]
Create Mod's redstone links have been broken in TARDIS refined's TARDIS dimensions, even since the 1.19.2 version (i discovered the bug then but didn't have a GitHub account) :/

**Comment by unknowObject** [comment]
> Create Mod's redstone links have been broken in TARDIS refined's TARDIS dimensions, even since the 1.19.2 version (i discovered the bug then but didn't have a GitHub account) :/

Thank god the bug was fixed in the latest 2.0.6 update 2 days ago.

**Comment by TARDISSYT** [comment]
> > Create Mod's redstone links have been broken in TARDIS refined's TARDIS dimensions, even since the 1.19.2 version (i discovered the bug then but didn't have a GitHub account) :/
> 
> Thank god the bug was fixed in the latest 2.0.6 update 2 days ago.

oh, nice

**Comment by Jeryn99** [comment]
Fixed
