### ISSUE TITLE
Tardis sometimes causes crash when attempting to leave.

### ISSUE THREAD

**Issue by Hot-M3ss** [CommandrMoose/TardisRefined#350]
### Issue description

Tardis caused the server to crash when I left it.
[---- Minecraft Crash Report ----.txt](https://github.com/user-attachments/files/16570802/----.Minecraft.Crash.Report.----.txt)

### Steps to reproduce

1. enter a tardis using a teleport command
2. attempt to exit (it appears to be random)

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.3.5

### Tardis Refined version

v2.0.4

**Comment by Jeryn99** [comment]
Hello, this is actually a incompatibility caused by luckperms

**Comment by Hot-M3ss** [comment]
Do I need to enable a specific command or do we need to remove luck perms?

**Comment by Jeryn99** [comment]
Straight up incompatible, removal is required
