### ISSUE TITLE
tardis is damaged

### ISSUE THREAD

**Issue by BitterBlaze** [CommandrMoose/TardisRefined#351]
### Issue description

Tardis is damaged permanently, on version 2.0.5 running Minecraft 1.20.1.

was in flight, PC update fucked with my Bluetooth, had to alt+F4 to leave the game to reboot for updates, once the pc was updated opened game, tardis acted as if it had crashed and it’s been over 49 mins of playtime since the incident 

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.3.5

### Tardis Refined version

v2.0.4

### Other relevant versions

Tardis Refined shows its version 2.0.5

**Comment by TARDISSYT** [comment]
if it was a server then it kept going and crash landed the TARDIS, but if it wasn't a server it just broke somehow

edit: you could try updating if that fixes it, I think this post is being ignored tho so idk

**Comment by Hot-M3ss** [comment]
yes this is still an issue.

**Comment by Jeryn99** [comment]
Looking into it now
