### ISSUE TITLE
TARDIS will switch skin variant when summoned with key on landing pads

### ISSUE THREAD

**Issue by Yuna-04** [CommandrMoose/TardisRefined#356]
### Issue description

Unsure if this happens when travelling in general but happens with every skin variant option such as the telephone booth, not just the police boxes.

Link to video showcasing bug: https://youtu.be/zjyxKnJ1seM

### Steps to reproduce

1. Place two landing pads down
2. Summon the TARDIS to either using a variant skin and it'll change

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.3.1

### Tardis Refined version

v2.0.6

**Comment by 50ap5ud5** [comment]
Thanks, are you able to reproduce this when only TARDIS Refined is installed, without any other mods?

**Comment by Yuna-04** [comment]
> Thanks, are you able to reproduce this when only TARDIS Refined is installed, without any other mods?

Hey, so I have tried summoning the TARDIS in a fresh 1.20.1 game with no other mods installed and the issue seems to still happen. Also worth noting again this happens with every exterior, not just the police boxes. Attached video shows.

Vid: https://youtu.be/Ug3M2wZ-Gu0

**Comment by Yuna-04** [comment]
- Also just found this out, this bug happens when you change the TARDIS interior as well.

**Comment by 50ap5ud5** [comment]
Thanks for testing that out, we'll look into it. We had previously been updating our exterior placement logic to fix some other issues but this one may have fallen through.
