### ISSUE TITLE
Anti-aliasing disabled 

### ISSUE THREAD

**Issue by JFT003** [CommandrMoose/TardisRefined#358]
### Issue description

When the mod is installed everything becomes horribly jagged and screen door-ey.
![2024-09-03_02 06 43](https://github.com/user-attachments/assets/356942ea-afcc-4aa4-9330-71a8ab196313)

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.16.3

### Tardis Refined version

v2.0.6

**Comment by Jeryn99** [comment]
Not sure what I am looking at - perhaps provide a before and after?

**Comment by JFT003** [comment]
![image](https://github.com/user-attachments/assets/ecc85f04-1183-41fb-a457-28303eac4dee)
the treeline is probably the easiest difference to spot, how the leaves eventually start to become one big bulk instead of remaining, leafy. please let me know if this is still not enough

**Comment by Jeryn99** [comment]
I'm still not really sure what I am looking at aha (I play this game sparingly, not as into it as I used to be)
I was after a screenshot with and without the mod in the same spot if that makes sense?

I see you have, what I assume to be, Create installed aswell

I recommend making the screenshots in a new world


 Strange question, is this with Quilt or Fabric? We saw this on quilt once before

**Comment by JFT003** [comment]
hi, sorry for the red herring. That is a sc from a installation with create yes, myb. The first one is from a fabric isolated instance i created with just fabric api and TR, here is the sc with TR uninstalled. soz again.
![2024-09-03_05 29 24](https://github.com/user-attachments/assets/647cb7f7-73f6-4104-85f5-539574c7b056)

**Comment by Jeryn99** [comment]
Fixed, stupid walter white

**Comment by JFT003** [comment]
Thank you so much.
