### ISSUE TITLE
waypoints keep resetting

### ISSUE THREAD

**Issue by GameRZ55** [CommandrMoose/TardisRefined#359]
### Issue description

when i use a waypoint it works the first time. but after moving away from it, for some reason it resets to that next point and stays that way

### Steps to reproduce

1. save waypoint
2. use waypoint
3. go elsewhere with the tardis
4. waypoint is broken

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

0.15.11

### Tardis Refined version

v2.0.6

### Other relevant versions

i am playing on a modpack on top of the tardis refined mod, but i hardly think its related

**Comment by Jeryn99** [comment]
Fixed
