### ISSUE TITLE
Unable to quit to Main Menu.

### ISSUE THREAD

**Issue by FloppaVibes** [CommandrMoose/TardisRefined#36]
Upon loading a world and leaving, it gets stuck on Saving World
Being Unable to Leave a World with the Tardis Refined Mod Enabled

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a World 
2. Load in
3. Save and Quit to Menu
4. Get Stuck On saving world

**Expected behavior**
To be sent to the Main Menu

**Screenshots**
![image](https://user-images.githubusercontent.com/121738449/210158810-cc95c9b6-9a2c-481a-9565-6de27f08cfe8.png)

**Platform:**
1.19.2
Forge

**Additional context**
RandomTickSpeed was at max number of 9s

**Comment by CommandrMoose** [comment]
Thanks for using the template. Are you able to recreate this in a new world?

**Comment by FloppaVibes** [comment]
Yes.

**Comment by CommandrMoose** [comment]
The only thing I can recommend at this time is to ensure you reset your tick speed.

**Comment by CommandrMoose** [comment]
Closing this issue has there has not been any more updates.
