### ISSUE TITLE
Tardis activation sound keeps playing

### ISSUE THREAD

**Issue by GameRZ55** [CommandrMoose/TardisRefined#360]
### Issue description

every time i enter my tardis again after leaving and i interact with the console it activates the tardis again

### Steps to reproduce

1. exit the TARDIS
2. enter the TARDIS
3. interact with the console
4. activation happens again

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

0.15.11

### Tardis Refined version

v2.0.6

**Comment by Jeryn99** [comment]
Not a bug
