### ISSUE TITLE
Lost tardis key and locked tardis door

### ISSUE THREAD

**Issue by BlackJack4474** [CommandrMoose/TardisRefined#363]
### Issue description

I locked the tardis and long story short, I died and lost the key and can no longer get back into the tardis unless there is?

### Steps to reproduce

Quite easy, lock the tardis door with the key which you already assigned to the tardis, throw the key in lava and there you go.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 43.0.3

### Tardis Refined version

v2.0.6

### Other relevant versions

Prob the same on all versions

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

N/A

**Comment by Jeryn99** [comment]
Hey,
There is no way to enter a locked TARDIS at present (in Survival), this would defeat the purpose of a locked TARDIS

You will need to teleport back into your TARDIS with commands, ``/tardis_refined interior INTERIOR_ID_HERE`` and making a new key

I advise creating copies of your keys in future,

Thanks,
Jeryn
