### ISSUE TITLE
mod compatibility issues

### ISSUE THREAD

**Issue by WoLF-Senpai** [CommandrMoose/TardisRefined#364]
### Issue description

In my Modpack [The Dragons Den](https://www.curseforge.com/minecraft/modpacks/the-dragons-den) 
I have the [Diagonal Windows Mod](https://www.curseforge.com/minecraft/mc-mods/diagonal-windows), along with [Tardis Refined](https://www.curseforge.com/minecraft/mc-mods/tardis-refined), and I have noticed that the **Astral Manipulator** does not detect the glass window pane for the **Terraformer**﻿, as the Diagonal Windows Mod converts vanilla glass over to Diagonal Windows the moment you place them in the world 

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.2.20

### Tardis Refined version

v2.0.6

**Comment by Jeryn99** [comment]
2.0.7 is the latest release - have you tested with that?

**Comment by Y3NOX** [comment]
I also am having the same issue, I also have diagonal windows installed.  after uninstalling the windows mod, it fixed the issue.

**Comment by Jeryn99** [comment]
Seems I fixed it for diagonal walls, but not fences or windows 

yi yi yi
