### ISSUE TITLE
Astral Manipulator selection is non-functional on a server, but works fine on singleplayer

### ISSUE THREAD

**Issue by anquietas-sys** [CommandrMoose/TardisRefined#369]
### Issue description

Astral Manipulator selection is non-functional on a server, but works fine on singleplayer.
When trying to select an area on a server, the second click does not change the bounding box of the selection as it should, it never gets to the third step.

### Steps to reproduce

1. run the server
2. join the server
3. try to use the astral manipulator
4. see that you cannot properly select an area

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

magma-1.20.1-47.2.20-b4bdd80-server.jar

### Tardis Refined version

v2.0.7

### Other relevant versions

https://github.com/user-attachments/assets/7551d3d5-45a3-4aa6-ab23-0284c8e35d51

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

N/A

**Comment by anquietas-sys** [comment]
Yes, this is still broken.

**Comment by Jeryn99** [comment]
Hey, just got round to this issue properly, I see by ``magma-1.20.1-47.2.20-b4bdd80-server.jar`` that you are using some form of Hybrid server and we cannot accept this issue report due to the invasive nature of them

Please re-test with native forge/fabric/neoforge
