### ISSUE TITLE
Some tags might broken with mod compact, without compacted mod installed.

### ISSUE THREAD

**Issue by NotShaung** [CommandrMoose/TardisRefined#373]
### Issue description

The mod compact cause tags missing report if don't have compacted mod installed.
I installed TARDIS Refined 2.0.7 without Create mod installed, missing tag warning will popup.

### Steps to reproduce

1. Install TARDIS Refined 2.0.7 version, with [Load My F***ing Tags](https://modrinth.com/mod/lmft) but without Create mod.
2. Open and world save (or just create new save).
3. Log have Create mod tags missing warning.

### Minecraft version

1.20.1

### Mod Loader Platform type

Neoforge

### Mod Loader version

NeoForge 47.1.106

### Tardis Refined version

v2.0.7

### Other relevant versions

[Create](https://modrinth.com/mod/create) 0.5.1.h
[Load My F***ing Tags](https://modrinth.com/mod/lmft) 1.0.4+1.20.1

**Comment by Jeryn99** [comment]
No log?

I have no understanding of any of what you're telling me

**Comment by NotShaung** [comment]
At line 1617
https://gist.github.com/NotShaung/ce12ae2fed149c666b969e7eeb19f60e

Sorry, I'm not quite sure how to explain this issue in the simplest way.

**Comment by Jeryn99** [comment]
Fixed!
