### ISSUE TITLE
(forge) Valkyrien Skies compatability

### ISSUE THREAD

**Issue by labmonjos** [CommandrMoose/TardisRefined#375]
### Issue description

When using this mod (v2.0.7) and the latest Valkyrien Skies (2.3.0 beta 5) for Forge, I get the same crash as defined in https://github.com/WhoCraft/TardisRefined/issues/352 and https://github.com/WhoCraft/TardisRefined/issues/324 when using sheers on the fully grown root. This issue does not appear with Valkyrien Skies uninstalled.

I see here: https://github.com/WhoCraft/TardisRefined/pull/362 it was fixed, but i assume this was for the fabric version only, as I am using Forge and the game crashes when sheering the Root.

not sure if this is the same bug that was fixed in the fabric version, but I wanted to bring it to your attention if it is.

### Steps to reproduce

Let the root grow
Shear root
Game crashes

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.3.7

### Tardis Refined version

v2.0.7

### Other relevant versions

Valkyrien Skies (2.3.0 beta 5)

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/igh8m4hF

**Comment by Jeryn99** [comment]
The fix hasn’t been released….
