### ISSUE TITLE
Trying to sheer off roots kicks me out of the world

### ISSUE THREAD

**Issue by jlawesome** [CommandrMoose/TardisRefined#378]
### Issue description

So when I try to sheer off roots off of the front door of the Root Shell it kicks me out of the world and I then am kicked to the multiplayer failed to connect screen

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.3.7

### Tardis Refined version

v2.0.7

**Comment by Jeryn99** [comment]
Damn, no logs or mod list?
Provide so we can help

**Comment by jlawesome** [comment]
Sorry took me a while to respond, heres the mod list at least, don't have any crash logs because its not crashing the game
[Modlist.pdf](https://github.com/user-attachments/files/17355066/Modlist.pdf)

**Comment by Jeryn99** [comment]
You must provide logs from the logs folder

**Comment by jlawesome** [comment]
[2024-07-04-1.log.gz](https://github.com/user-attachments/files/17355080/2024-07-04-1.log.gz)

**Comment by Jeryn99** [comment]
This log is majorly out of date. Launch the game, recreate the problem, close the game and provide latest.log not a .gz file

**Comment by jlawesome** [comment]
[latest.log](https://github.com/user-attachments/files/17355106/latest.log)

**Comment by Jeryn99** [comment]
Valkyrien Skies in current releases is not compatible with Tardis Refined due to some strange code that has been patched in a upcoming release in this commit https://github.com/WhoCraft/TardisRefined/commit/9f4bc97a5c61e3152a5b1ec08d7e0a8f3ee7ac53

Please wait for the next release
