### ISSUE TITLE
[BUG] Takeoff sound overlaps with in-flight sound

### ISSUE THREAD

**Issue by thejudge156** [CommandrMoose/TardisRefined#38]
**Describe the bug**
When initially taking off, the in-flight sound plays along with the takeoff sound, causing a sort of reverb.

**To Reproduce**
1. Takeoff
2. Listen

**Expected behavior**
Takeoff sound, THEN the in-flight sounds

**Platform:**
 - Game version: 1.19.2
 - Platform: Fabric

**Comment by CommandrMoose** [comment]
This is intentional, and is infact a bug that it doesn't continue when landing. Thanks for using the template!

**Comment by thejudge156** [comment]
If I may ask, why is this?
