### ISSUE TITLE
Console cannot be removed/changed with the console configurator outside of the tardis dimension

### ISSUE THREAD

**Issue by DaPuffer** [CommandrMoose/TardisRefined#380]
### Issue description

The title. Even when correctly placed,the console configurator does nothing to the console,making accidental console placements in dimensions outside the tardis,pretty much permanent.
This issue was already mentioned,but it was in version 2.0.3 of the mod.
https://github.com/WhoCraft/TardisRefined/issues/316#issue-2352932023

### Steps to reproduce

1.Place a console/craft it using the astral manipulator
2.Place a console configurator facing towards it
3.Try to change/break the console with the configurator
4.Nothing happens.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.3.7

### Tardis Refined version

v2.0.7

**Comment by Jeryn99** [comment]
Give me a screenshot of your placement please

**Comment by DaPuffer** [comment]
![2024-10-17_23 46 57](https://github.com/user-attachments/assets/7ccc6816-22c4-46f7-94e9-141e12c48b55)

**Comment by Jeryn99** [comment]
Not sure why you need this, but fixed!
