### ISSUE TITLE
immersive portals cloned doors 

### ISSUE THREAD

**Issue by YukeinPower** [CommandrMoose/TardisRefined#382]
### Issue description

after opening the TARDIS for the first time some doors get duplicated and is more notorius after the desktop configuration process
(in my case the watchface) and in others there is a floting console (the original console) over the alredy selected one

![Captura de pantalla 2024-10-16 162615](https://github.com/user-attachments/assets/8e164d81-76db-405c-809c-fa82c6ffa9c5)

note: after experimenting with the other configs the bug seem to fix by itself

### Steps to reproduce

- create the fabric tardis
- power up the tardis

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric - 0.16.7

### Tardis Refined version

v2.0.7

### Other relevant versions

affected deskt configurations

- radiance
- future nos
- crystal
- refurbished
- copper
- vapor (stuck in the tardis)
- watchface

examples:
![Captura de pantalla 2024-10-16 163026](https://github.com/user-attachments/assets/d0737459-d547-4e2d-9acf-7c9ec67cd9dc)
![Captura de pantalla 2024-10-16 161410](https://github.com/user-attachments/assets/4d67d926-db47-4478-87f3-92827221d187)
![Captura de pantalla 2024-10-16 162252](https://github.com/user-attachments/assets/0e0ed73a-02b5-4a98-af9b-63747c857a6f)

**Comment by Jeryn99** [comment]
Yeah we've seen this occur and we have no idea why it happens, we may need to talk to the IP developers on this one

**Comment by Jeryn99** [comment]
I will be moving all IP stuff here https://github.com/WhoCraft/TardisRefined/issues/368
