### ISSUE TITLE
[Incompatibility] Diagonal Windows makes it impossible to craft the terraformer

### ISSUE THREAD

**Issue by SamuelAsteroid** [CommandrMoose/TardisRefined#383]
### Issue description

https://modrinth.com/mod/diagonal-windows

Because of how the diagonal windows mod works, it replaces every placed glass pane with the mods version instead making the craft of the terraformer not recognize their glass panes as actual glass panes and thus unable to make a terraformer.

### Steps to reproduce

1. Install Tardis Refined and Diagonal Windows
2. Use the Astral Manipulator and try to create the Terraformer
3. Failed to craft

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

0.16.4

### Tardis Refined version

v2.0.7

### Other relevant versions

Diagonal Windows by Fuzs v8.1.4

**Comment by TARDISSYT** [comment]
Comment removed due to me embarrassing myself. Also deleting new comments on other posts I made that are what @Jeryn99 said below.

**Comment by Jeryn99** [comment]
@TARDISSYT, please refrain from participating in our issue trackers without providing accurate and factual information. Additionally, please refrain from using swear words in your contributions. If you intend to censor certain words, there’s no point in using those certain words 

Regardless, this oversight is easily fixable, and we expect it to be resolved in the next release.

**Comment by Jeryn99** [comment]
Fixed in https://github.com/WhoCraft/TardisRefined/commit/6bba34356cc2c064b7ee24983dff15b3e13f9215
