### ISSUE TITLE
let people type coordinates

### ISSUE THREAD

**Issue by Durzan12** [CommandrMoose/TardisRefined#385]
### Issue description

please make it so that we can type coordinates much faster, and make the tardis less complicated

### Minecraft version

1.20.1

### Mod Loader Platform type

Neoforge

### Mod Loader version

Forge

### Tardis Refined version

v2.0.7

**Comment by CommandrMoose** [comment]
Our issue tracker is not a place for suggestions.

Please refer to our discord or the Curseforge page for stuff like this...


where we will tell you no anyway because we wish for the buttons to be the way you input coordinates.
