### ISSUE TITLE
Visual Compatibility with Shaders

### ISSUE THREAD

**Issue by Nicaditto** [CommandrMoose/TardisRefined#386]
### Issue description

I play with shaders on, but the console look very weird with it. The colors are weird and turn black and white. In the screenshot, I currently use Complementary. I try with a low-end shader like make up UF and the problem still persist. Other thing was the fx particle sometimes get invisible when flight event occurs so i cant see what's error (i had the glasses on).
![Screenshot 2024-11-03 231512](https://github.com/user-attachments/assets/fff386cc-3b4e-4f47-bfae-67b84cad5028)

Does this mod best to play with vanilla shader (no support for any modded shaders) or any recommendation of another shader that support it? 

### Steps to reproduce

1. Change to any shader (Complementary, Make Up UF [my case])
2. Dissatisfaction seeing the console

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge v47.0.45

### Tardis Refined version

v2.0.7

**Comment by Jeryn99** [comment]
## How to Add Custom Item to Shader Properties

1. **Open Complementary Shaders Folder**  
   - Locate and open the folder containing Complementary shaders.

2. **Navigate to the `shaders` Folder**  
   - Inside the main shader folder, find and open the folder named `shaders`.

3. **Locate `block.properties` File**  
   - Look for a file named `block.properties` (or something similar) within the `shaders` folder.

4. **Open `block.properties` in a Text Editor**  
   - Use a suitable text editor to open `block.properties` for editing.

5. **Search for "chest"**  
   - In the `block.properties` file, search for the keyword "chest" to locate the section that defines properties for regular and trapped chests.

6. **Add Custom Item to Chest Section**  
   - Add `tardis_refined:tardis_console` to the list in the chest section. Make sure to follow the same format as the other entries.

7. **Save the File**  
   - Once the changes are made, save the `block.properties` file.

8. **Test in Game**  
   - Load the shaders in-game to check if the changes took effect. If there are any issues, further adjustments may be needed.

> **Note:** If you encounter issues, let me know, and I can provide a modified `block.properties` file as a reference.

---

This process should work for other shaders as well, but note that each shader may have different ways of handling data, so adjustments might vary.

**Comment by Nicaditto** [comment]
It fixed the lighting issue but the coloring is still weird
![image](https://github.com/user-attachments/assets/d03074de-8a18-4c6e-8380-b09080fe4b31)

**Comment by Jeryn99** [comment]
Unfortunately, shaders isn't something we have much control over
