### ISSUE TITLE
[Farbic] Exception Ticking World

### ISSUE THREAD

**Issue by Ksdron** [CommandrMoose/TardisRefined#388]
### Issue description

Server crashed after someone attempted to initiate Tardis flight. Happened again 2 days later.

First crash happened to me right as the flight started. First attempt to fly the Tardis. Issue did not re-occur after subsequent flights after server restart. Attempted to switch to the AR Glasses as flight begun.

Second Crash happened to a friend, who was flying repeatedly to grind xp. On their 20th flight, server crashed. Did nothing apparently different from other flights.

Attached are the 2 crash logs for these events:

[crash-2024-11-12_04.46.39-server.txt](https://github.com/user-attachments/files/17712548/crash-2024-11-12_04.46.39-server.txt)
[crash-2024-11-10_23.29.19-server.txt](https://github.com/user-attachments/files/17712549/crash-2024-11-10_23.29.19-server.txt)

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader Version 0.16.7

### Tardis Refined version

v2.0.7

**Comment by Jeryn99** [comment]
I feel I may have fixed this already for the next update
