### ISSUE TITLE
[VR/Forge] Difficulty Seeing Outside TARDIS Door Without Immersive Portals Mod – Risk of Collision/Lava Exposure

### ISSUE THREAD

**Issue by thankfuldeadman** [CommandrMoose/TardisRefined#389]
### Issue description

When playing without the Immersive Portals mod, players are unable to see what’s directly outside the TARDIS before exiting, as the door appears black or doesn’t show the external view. This creates a challenge in unfamiliar or dangerous locations, where players risk walking into hazards like lava or solid walls immediately after stepping out.

Proposed Solution:
To make gameplay safer and more intuitive, it would be helpful if a feature could be added to preview the area directly outside the TARDIS. Possible ideas include:

A display on the TARDIS desktop that shows nearby block types, biome, or immediate surroundings.
An option to generate a static image or short GIF preview of the first few blocks outside.
Environment:

Forge Loader (without Immersive Portals mod)
Occurs for both VR and desktop players

### Steps to reproduce

Load Tardis Refined on Forge Loader without using the Immersive Portals mod.
Position the TARDIS in any area with potentially hazardous surroundings (e.g., near lava, cliffs, or inside a cave with walls close by).
Attempt to exit the TARDIS. Observe that the door does not provide a view of the outside environment; instead, it appears black.
Step outside the TARDIS to experience the unexpected surroundings, which could lead to walking into hazards or walls.
Expected Behavior:
A way to preview or get a sense of the external environment around the TARDIS before exiting, to avoid accidental collisions or stepping into dangerous areas.

### Minecraft version

1.20.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

47.3.0

### Tardis Refined version

v2.0.7

**Comment by Jeryn99** [comment]
I am not sure how it will act in VR due to them changing a lot of the game, it utilizes third person but I have implemented something! :)

**Comment by thankfuldeadman** [comment]
has it been tested in vr and if so how did it go?

**Comment by Jeryn99** [comment]
It has not, my quest is screaming for updates which lead it it screaming for app updates so not really had the chance 

I can hand something to you specifically for testing if you find me on the discord tomorrow @thankfuldeadman

**Comment by thankfuldeadman** [comment]
okay will do I
