### ISSUE TITLE
Tardis will get stuck at 0, 0, 0 coordinates

### ISSUE THREAD

**Issue by The-Rose-Composer** [CommandrMoose/TardisRefined#390]
### Issue description

There will very rarely be this glitch where when I land the Tardis, it will replace the coordinates that I set (for example the coordinates 1000, 60, 1000) with the coordinates 0, 0, 0, and the Tardis will land underground, often in a solid block depending on the world generation. When I try and set the coordinates to something else and land another time, it will again default to 0, 0, 0. This will happen a number of times until eventually the coordinates I set do stay and the Tardis can be moved elsewhere. I have only experienced this bug on the latest release of Tardis Refined for Forge, and I haven't seen anyone else report a similar bug, so I thought I would ask here. It's not any big bug but I was wondering if there is any specific thing that I keep doing that is making this happen. (This mod actually has very few bugs from what I've seen from playing, so good job devs!)

### Steps to reproduce

1. Set the Tardis Coordinates to any location
2. Dematerialize and Rematerialize
3. The Tardis will randomly materialize at 0,0,0 and you cannot set the coordinates anywhere else. (Keep in mind that this doesn't happen very often, but I have encountered it a few times just by playing normally.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.3.0

### Tardis Refined version

v2.0.7

**Comment by Jeryn99** [comment]
0,0,0 is our fallback if the Tardis Data get's nullified for whatever reason - this is definitely something I will look into

**Comment by SuperKnux** [comment]
noticing this error on 2.1.0 on 1.20.1 Fabric, TARDIS gets stuck at 0, 0, 0 coords facing Down (despite me using the Present), and the Direction switch doesn't seem to do anything.

**Comment by Jeryn99** [comment]
> noticing this error on 2.1.0 on 1.20.1 Fabric, TARDIS gets stuck at 0, 0, 0 coords facing Down (despite me using the Present), and the Direction switch doesn't seem to do anything.

Facing down? Could I have a video of the issue?

**Comment by SuperKnux** [comment]
[Link to the video I made](https://streamable.com/pyyvku)
it appears that only waypoints are broken. I was able to send the tardis to a hardcoded location just fine.

**Comment by Jeryn99** [comment]
Okay, that's actually really helpful, thank you! 

So basically, you can always travel to any inputted coordinates, but never waypoints?

**Comment by SuperKnux** [comment]
yep!
it appears to be when the given direction for the waypoint is "Down"

**Comment by Jeryn99** [comment]
@SuperKnux Does this only happen with old waypoints from before 2.1.0 or new ones?

**Comment by SuperKnux** [comment]
the waypoints were reset when i updated to 2.1.0, this "Down" default never occurred until then.

**Comment by Jeryn99** [comment]
Is this issue present in https://github.com/WhoCraft/TardisRefined/releases/tag/v1.20.1-2.1.2?

**Comment by VilcsiTH** [comment]
This is still present in 2.1.3 forge, updated the server from 2.0.7, setting waypoints doesn't change coordinates at all, manually changing X Y Z does change them, and you can fly with the tardis, but they're immediately zero'd as soon as the flight is over. I can use commands to get inside the interior, but the police box is not where I left it in the overworld before the update - I do not think it even exists in the overworld anymore.
Unlocking landing pad with commands and then summoning the tardis fixed the issue.

**Comment by Jeryn99** [comment]
Are these waypoints from 2.0.7? You may need to remake them as some data stuff changed - I think I may have put a note in the changelog about it

**Comment by VilcsiTH** [comment]
Good call - trying to set the waypoint zeros out the destination. I've deleted it and created a new one, the waypoint is now being set normally.
