### ISSUE TITLE
Tardis Crashes Server When Taking off

### ISSUE THREAD

**Issue by Starrisky420** [CommandrMoose/TardisRefined#392]
### Issue description

When entering the TARDIS and pulling the lever to start flight it crashes my server

### Steps to reproduce

1. Enter TARDIS
2. Close TARDIS door
3. Walk up to the lever and pull it
4. Server crashes

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader Version 0.15.11

### Tardis Refined version

v2.0.7

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/NS4MUgbX

**Comment by Jeryn99** [comment]
Which exterior shell was this?

**Comment by Starrisky420** [comment]
Exterior
![image](https://github.com/user-attachments/assets/75a77d9c-4f51-4fea-9fe2-85d77aee1088)

Interior
![image](https://github.com/user-attachments/assets/905e01f6-c95d-430a-b075-f85ed1f247d7)

**Comment by Jeryn99** [comment]
Fixed this a while ago! Just seems to not be released!
