### ISSUE TITLE
Bug Report: Shears Crash the Server

### ISSUE THREAD

**Issue by thankfuldeadman** [CommandrMoose/TardisRefined#394]
### Issue description

Using shears causes the server to crash immediately. This happens consistently when the shears are used on the Tardis. The error points to ConstraintFailedException and involves server tick loops. Crash Report: [PRE_TICK, GET_LAST_TICK_CHANGES, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, UPDATE_CHUNKS, POST_TICK_START, POST_TICK_GENERATED, POST_TICK_FINISH, GET_CURRENT_TICK_CHANGES, CLEAR_FOR_RESET, UPDATE_DIMENSIONS, UPDATE_PLAYERS] and also a link 
[Tardis adventure 1.zip](https://github.com/user-attachments/files/17964327/Tardis.adventure.1.zip)

### Steps to reproduce

1.Enter Creative mode.
2.Spawn a TARDIS shell.
3.Use shears on the TARDIS shell.
4.Observe the server crash.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.3.0

### Tardis Refined version

v2.0.7

**Comment by Jeryn99** [comment]
Is this with valkerian skies installed?

**Comment by thankfuldeadman** [comment]
Yes, I’ve isolated different mods in my mod pack and found that the issue was caused by incompatibility with Valkyrien Skies.I think the problem has to do with the UPDATE_CHUNKS and POST_TICK_* stages failing. A ConstraintFailedException in Valkyrien Skies seems to be its way of halting when something goes beyond its expected rules.

**Comment by Jeryn99** [comment]
This will be fixed when #379 is merged and released!
