### ISSUE TITLE
Terraformer not crafting

### ISSUE THREAD

**Issue by ReubenJ129** [CommandrMoose/TardisRefined#395]
### Issue description

When I put the crafting recipe for the terraformer into a crafting table, nothing happens.

### Steps to reproduce

1. Place items into position in the crafting table

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge version 47.3.0

### Tardis Refined version

v2.0.7

**Comment by Jeryn99** [comment]
https://wiki.tardisrefined.net/astral-manipulator-recipes.html#terraformer
