### ISSUE TITLE
Tardis Crashes When Taking off (NeoForge)

### ISSUE THREAD

**Issue by NotShaung** [CommandrMoose/TardisRefined#397]
### Issue description

When I entering the **TARDIS** and pulling the lever to start flight it crashes my game.

I know it might seems similar issue like this one
https://github.com/WhoCraft/TardisRefined/issues/392

but this happened on Neoforge loader I report it want make sure is it completely same.

### Steps to reproduce

1. Enter TARDIS.
2. Start take off.
3. Game crash after start take off.

note:
I have preset navigation points before reaching my last goal.

### Minecraft version

1.20.1

### Mod Loader Platform type

Neoforge

### Mod Loader version

NeoForge 47.1.106

### Tardis Refined version

v2.0.7

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://gist.github.com/NotShaung/a06845515f2f3655fe8b00127f46a5f2

**Comment by Jeryn99** [comment]
Fixed in next update
