### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by GreaterCreationYT** [CommandrMoose/TardisRefined#399]
### Issue description

Game crashes randomly when entering Coral Tardis (unterraformed)

### Steps to reproduce

1: place root shell block (creative)
2: shear root shell
3: walk inside root shell

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

fabric-0.16.9

### Tardis Refined version

v2.0.7

### Other relevant versions

Latest full release of Immersive Portals as of 12/3/2024

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://gist.github.com/GreaterCreationYT/11a561879eeb2d5045706aaa9cb0fc4e#file-gistfile1-txt

**Comment by Jeryn99** [comment]
Doesn't seem to be a issue with us according to the log, can you re-produce and provide another?

**Comment by CommandrMoose** [comment]
This issue stems from Immersive Portals and can happen on certain NVIDIA GPUs. If you're running with one, I recommend installing mods like Sodium and other performance mods. This has helped me in the past.
