### ISSUE TITLE
Glasses slot issue 

### ISSUE THREAD

**Issue by Aiko0508** [CommandrMoose/TardisRefined#405]
### Issue description

I have curios and the tardis mod, but there's no alot for the glasses and it won't fit on my head. I tried using commands on my server to add a slot for it but there's no option labeled for the glasses. Plz help.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.3.0

### Tardis Refined version

v2.0.7

**Comment by CommandrMoose** [comment]
This is an upcoming feature in our next update. Thanks for the report!
