### ISSUE TITLE
Crash on world loading due to "controllerConsole is null"

### ISSUE THREAD

**Issue by 20njackman** [CommandrMoose/TardisRefined#411]
### Issue description

Tardis landed after long flight (50,000 blocks) to location previously explored/loaded, and game immediately crashed. Upon trying to reload the world, it crashes immediately. I am using the Victorian console and desktop if that makes a difference.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge version 47.3.12

### Tardis Refined version

v2.0.7

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/HTh8U5EV

**Comment by Jeryn99** [comment]
Is fixed next version!
