### ISSUE TITLE
Tardis Dupe/Door Glitch 

### ISSUE THREAD

**Issue by higuysitsmesgragen** [CommandrMoose/TardisRefined#412]
### Issue description

First time I flew the Tardis, it went fine, but when I returned back to the place we took off from, the Tardis had duped itself and there were two of them. The other one suddenly disappeared. And then, when I went back inside, the door wouldn’t work to anything but the door switch. I had to break it and remake it. 

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 1.20.1??

### Tardis Refined version

v2.0.7

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)
[message.txt](https://github.com/user-attachments/files/18220595/message.txt)

**Comment by Jeryn99** [comment]
This is addressed in the next update already
