### ISSUE TITLE
Compatibility with ad astra is broken.

### ISSUE THREAD

**Issue by AlexTardisHbn** [CommandrMoose/TardisRefined#414]
### Issue description

I've just upgraded the version of "Tardis Refined" and I can't anymore start my dedicated server.

### Steps to reproduce

- Update the mod
- Try to start the server
- Nothing

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader Version 0.16.9

### Tardis Refined version

v2.0.7

### Other relevant versions

Version of Tardis Refined "2.1.0"

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/Au422Gat

**Comment by Jeryn99** [comment]
Are you sure this isn't a install issue with your server? You seem to be missing a library that Minecraft uses?

![image](https://github.com/user-attachments/assets/d3577f36-b3b1-4728-9787-b5fa87fc6bd2)

**Comment by Jeryn99** [comment]
I have modified the class so it no longer uses this library, enjoy 

Re-download the mod :)
