### ISSUE TITLE
Model Doesn't Properly Renderer after TARDIS Growth?

### ISSUE THREAD

**Issue by MaketendoDev** [CommandrMoose/TardisRefined#415]
### Issue description

Crashes the game as soon as the TARDIS finish refining by the Terraformer (keeps on crashing when the game loads back in to render it)

Launcher Error:
The game crashed whilst rendering block entity
Error: java.lang.IllegalAccessError: failed to access class net.minecraft.client.model.geom.ModelPart$Vertex from class whocraft.tardis_refined.client.model.pallidium.ExtendedCubeListBuilder$PerFaceUVCube (net.minecraft.client.model.geom.ModelPart$Vertex is in module minecraft@1.20.1 of loader 'TRANSFORMER' @197cc325; whocraft.tardis_refined.client.model.pallidium.ExtendedCubeListBuilder$PerFaceUVCube is in module tardis_refined@2.1.0 of loader 'TRANSFORMER' @197cc325)

### Steps to reproduce

1. Terraform da TARDIS
2. Bombastically Crash

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

forge-47.3.0

### Tardis Refined version

v2.0.7

### Other relevant versions

Actually 2.1.0 😎 I lied

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/tQRAEFFE

**Comment by Jeryn99** [comment]
Before reporting, did you re-download the mod?

**Comment by MaketendoDev** [comment]
I'm on curseforge so if you have recently I may have not gotten it, rn it says i'm on latest
