### ISSUE TITLE
Game crash when In tardis

### ISSUE THREAD

**Issue by Jocho-Winter** [CommandrMoose/TardisRefined#416]
### Issue description

Whenever I walk around or join the world my game crashes, I don't know why, I checked my crash log, and I don't know how to fix it
![image](https://github.com/user-attachments/assets/5cf406ed-65be-44b2-b2dd-12144bafdf91)
![image](https://github.com/user-attachments/assets/559fd656-aec4-4356-8388-4a618fab1d61)

### Steps to reproduce

1. Join world
2. freezes
3. Crashes

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.3.0

### Tardis Refined version

v2.0.7

### Other relevant versions

It is 2.1.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://gist.github.com/Jocho-Winter/0f2caed70ebb5a3e10fb70eb2a2ed473

**Comment by Jocho-Winter** [comment]
Sorry if I submitted it incorrectly

**Comment by Jeryn99** [comment]
Try this EXACT file and let me know if it solves your issue 

https://cdn.modrinth.com/data/nqVt6aES/versions/BVDku2IV/forge-tardis_refined-mc1.20.1-v2.1.0.jar

**Comment by Jocho-Winter** [comment]
nope sorry, it still crashes, same crash log too

**Comment by Jeryn99** [comment]
All sorted now, redownload

**Comment by Jocho-Winter** [comment]
tsym
