### ISSUE TITLE
Cannot create Console with Astral Manipulator

### ISSUE THREAD

**Issue by GreaterCreationYT** [CommandrMoose/TardisRefined#417]
### Issue description

When using the Astral Manipulator with the amethyst screwdriver, the console multiblock crafting recipe does not create the Console when selecting the correct blocks and confirming the selection.

https://github.com/user-attachments/assets/4a87cd4b-2d67-481c-b48d-ccb0d2eca077

Version of the mod is actually 2.1.0, not 2.0.7

### Steps to reproduce

1. Obtain the tardis
2. attempt the console crafting recipe with the astral manipulator

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

0.16.9

### Tardis Refined version

v2.1.0

### Other relevant versions

Unsure if it is related to other mods

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://gist.github.com/GreaterCreationYT/0c533a9e36bd5f86ec31b4575ddae4c9.js

**Comment by Jeryn99** [comment]
Thanks for reporting

**Comment by MidnightWolfang** [comment]
Same here, but can't build the terraformer
