### ISSUE TITLE
Fuel Indicator not showing Value

### ISSUE THREAD

**Issue by nnnGi** [CommandrMoose/TardisRefined#418]
### Issue description

When hovering over the fuel control on the Tardis Console, it Shows “Fuel: %” instead of the value. The same thing happens in the Shell View

### Steps to reproduce

TARDIS Control:
1. Make a TARDIS, fully upgrade it
2. Set to Toyota Console (No idea if this affects this)
3. Hover over Fuel Control

Shell View:
1. Make a TARDIS
2. Look At Fuel Indicator on Shell View

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.3.0

### Tardis Refined version

v2.1.0

### Other relevant versions

Includes TriadTech and WhoCosmetics

**Comment by Jeryn99** [comment]
Cannot Re-produce, is your default language English? (Leave a comment)

**Comment by nnnGi** [comment]
Yes It is English

**Comment by nnnGi** [comment]
Still present in 2.1.1
