### ISSUE TITLE
Opening door while Tardis is in flight with Immersive Portals mod breaking rendering

### ISSUE THREAD

**Issue by GreaterCreationYT** [CommandrMoose/TardisRefined#419]
### Issue description

When you open the door to the tardis with the immersive portals mod while you are in flight, it breaks and only renders outside of the portal (was attempting to see the time vortex from inside the tardis)

https://github.com/user-attachments/assets/4e16d4ac-e0a4-4fc9-a1ba-71066579dabd

### Steps to reproduce

1. open tardis door mid flight with immersive portals installed

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

0.16.9

### Tardis Refined version

v2.1.0

### Other relevant versions

Immersive Portals v3.3.9

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://gist.github.com/GreaterCreationYT/e52e91c41de9ff50e18ecda94666a5d1

**Comment by Jeryn99** [comment]
Likely linked to https://github.com/WhoCraft/TardisRefined/issues/423
