### ISSUE TITLE
[BUG] TARDIS can land on non-solid blocks

### ISSUE THREAD

**Issue by thejudge156** [CommandrMoose/TardisRefined#42]
**Describe the bug**
TARDIS can land on tall grass and other non-solid blocks

**To Reproduce**
1. Find a piece of grass
2. Get the coordinates of the grass block
3. Takeoff and Land

**Expected behavior**
Replace the grass or land around it.

**Screenshots**
![2023-01-02_20 26 03](https://user-images.githubusercontent.com/53906078/210300375-bb2b40b1-23ba-4a53-be8c-d8bfe0689aa4.png)

**Platform:**
 - Game version: 1.19.2
 - Platform: Fabric

**Comment by CommandrMoose** [comment]
Thanks for reporting this, we're looking into filtering what blocks would be considered to be overridden.

**Comment by thejudge156** [comment]
Fixed in #43
