### ISSUE TITLE
Door Disappears in Flight

### ISSUE THREAD

**Issue by nnnGi** [CommandrMoose/TardisRefined#420]
### Issue description

When Flying the TARDIS, the door disappears and reappears when landing

### Steps to reproduce

1. Make a TARDIS
2. Fly TARDIS

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.3.0

### Tardis Refined version

v2.1.0

### Other relevant versions

Includes TriadTech

**Comment by Jeryn99** [comment]
Is this in a Mac? Or Intel integrated graphics? (Yes you may have a graphics card, but have you told MC to use it?)

**Comment by nnnGi** [comment]
WhYes I use a Mac

**Comment by Jeryn99** [comment]
Can’t help you, you will need to disable the fancy rendering in the TARDIS Refined client config
