### ISSUE TITLE
Enter TARDIS with door closed

### ISSUE THREAD

**Issue by nnnGi** [CommandrMoose/TardisRefined#422]
### Issue description

When the TARDIS door is closed or locked, you can enter from the outside.

### Steps to reproduce

1. Make a TARDIS
2. Lock the TARDIS or Close the door
3. Walk into the shell ‘door’
4. Be teleported inside

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.3.0

### Tardis Refined version

v2.1.0

**Comment by Jeryn99** [comment]
What other mods do you have installed?

**Comment by nnnGi** [comment]
TraidTech
WhoCosmetics
Create

**Comment by Jeryn99** [comment]
Cannot re-produce - do you have immersive portals installed?

**Comment by nnnGi** [comment]
No ITS ON FORGE

**Comment by Jeryn99** [comment]
Which also has Immersive Portals 

but alas, there’s no need for caps lock 

Try update 2.1.1 and get back to me

**Comment by nnnGi** [comment]
There is Immersive Portals for Forge 1.20.1 now?
