### ISSUE TITLE
Shell View has Two TARDISES

### ISSUE THREAD

**Issue by nnnGi** [CommandrMoose/TardisRefined#424]
### Issue description

After landing the TARDIS, the overlay stays in the shell view (the overlay from the vortex) instead of disappearing.

### Steps to reproduce

1. Make a TARDIS
2. Fully upgrade it
3. Set a random destination
4. Fly
5. Enter shell view
6. Wait
7. Land
8. Enter shell view
9. Rotate the view to see the Overlay TARDIS

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.3.0

### Tardis Refined version

v2.1.1

### Other relevant versions

TriadTech

**Comment by Jeryn99** [comment]
Duplicate of https://github.com/WhoCraft/TardisRefined/issues/434
