### ISSUE TITLE
Using the amethyst screwdriver to interact with the terraformer causes a freeze crash. (v2.1.1)

### ISSUE THREAD

**Issue by NotShaung** [CommandrMoose/TardisRefined#426]
### Issue description

After the latest hotfix 2.1.1, using the amethyst screwdriver to interact with the terraformer results in a crash. 
However, it worked fine in version 2.1.0. I believe the 2.1.1 update might have introduced compatibility issues with certain other mods.

### Steps to reproduce

1. Place terraformer.
2. Using the amethyst screwdriver to interact with the terraformer.

Note: 
I tested on both 2.1.0 and 2.1.1 but it only happen on latest 2.1.1 version.
I also tested without other mods, and I know that v2.1.1 works fine without them.

And thank you for all your hard work on this mod. I hope all the issues can be resolved soon!

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

forge 47.3.0

### Tardis Refined version

v2.1.1

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://gist.github.com/NotShaung/9d5648e6183b8824061a301457adef13

**Comment by Jeryn99** [comment]
Re-Download the jar :)
