### ISSUE TITLE
Tardis cannot properly travel to other dimensions

### ISSUE THREAD

**Issue by The-Rose-Composer** [CommandrMoose/TardisRefined#430]
### Issue description

When you select what dimension you want the Tardis to land in, you can fly there however a number of weird things things seem to happen. The biggest problem is that when travelling to a different dimension, for example, X:200 Y:100 Z:200 in The Nether, when you exit the Tardis interior, it will put you to X:200 Y:100 Z:200 in the overworld. To make it clear, it will put you exactly at those coordinates, no matter if it is inside of a block or it is floating in the air. Meanwhile, in The Nether, the Tardis exterior will be at X:200 Y:100 Z:200. You can interact with the doors and go inside the Tardis, which will still teleport you to the interior, but the Tardis Shell will not make any noise when you open the doors and also will be stuck as the default Tardis Exterior no matter what you have selected (It's called Half-Baked in the menu). 

In addition to this, another weird problem with the dimensions is that the Tardis's own dimension will be on the list of dimensions that the Tardis can travel to. If you type in the coordinates of your console room and set the dimension to your Tardis dimension, it will land right next to you. (Kind of reminds me of that one episode haha)

The Tardis exterior also duplicated a few times in my testing, which only happened when I tried to land in other dimensions.
If you need the world file, etc. let me know (:

![2024-12-27_19 54 33](https://github.com/user-attachments/assets/028ac6ea-031c-443f-a0e0-0085ad0a7cb1)
![2024-12-27_19 55 20](https://github.com/user-attachments/assets/9c877687-fcfb-4d65-ac88-db657886cfd5)
![2024-12-27_19 58 49](https://github.com/user-attachments/assets/2f9c68a5-c452-4b46-94fe-5c9e2d1ae1b1)
![2024-12-27_20 01 33](https://github.com/user-attachments/assets/9fa77136-433b-49fe-837c-c033d8441b5c)

### Steps to reproduce

1. Select any dimension 
2. Take off and land in that dimension
3. Exit the Tardis and you will always be in the overworld
4. Teleport to the coordinates and dimension you set using commands to view the Tardis exterior

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.3.0

### Tardis Refined version

v2.1.1

**Comment by Jeryn99** [comment]
Try the versions from https://github.com/WhoCraft/TardisRefined/releases/tag/v1.20.1-2.1.2 and let me know!

**Comment by The-Rose-Composer** [comment]
I would say that the issue is pretty much resolved as after doing a lot of testing, I was able to travel to every dimension without any issues, however there is still two very small problems:

1. The Tardis dimension(s) are still on the dimensions list which I don't think is right, but I may be wrong. You can travel inside of your own Tardis or any other Tardis's that exist in the world.

2. I did almost all of my testing this time without using the shell viewer, but the few times I did use it, the Tardis would put you in the overworld after you exit the viewer (pressing tab). I noticed that if I was standing in the console room at, for example X:4 Y:100 Z:5, and then entered the shell viewer, when I exited it, it would put me at X:4 Y:100 Z:5 in the overworld, not in the Tardis dimension.

Apart from that, the entire bug is gone, and dimensional travel is fixed!

**Comment by Jeryn99** [comment]
Time for you to make a new issue for that haha 😅
