### ISSUE TITLE
Crash loop when using the console changer

### ISSUE THREAD

**Issue by XhRebirth** [CommandrMoose/TardisRefined#432]
### Issue description

Got a crash loop when cycling through the console changing block and cant access my world anymore

### Steps to reproduce

1. placing the block next to the console
2. right click to cycle between consoles

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.3.22

### Tardis Refined version

v2.1.1

### Mod List

    - advancementplaques 1.6.7
	- alexscaves 2.0.2
	- ambientsounds 6.1.4
	- ante 1.1
	- appleskin 2.5.1+mc1.20.1
	- aquaculture 2.5.1
	- aquaculturedelight 1.0.0
	- architectury 9.2.14
	- athena 3.1.2
	- attributefix 21.0.4
	- autohud 8.0
	- backported_wolves 1.0.3-1.20.1
	- badmobs 19.0.2
	- badpackets 0.4.3
	- balm 7.3.10
	- bellsandwhistles 0.4.3-1.20.x
	- betteranimationscollection 8.0.0
	- betterarcheology 1.2.1-1.20.1
	- betterbeaconplacement 3.4
	- bettercombat 1.8.6+1.20.1
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.4
	- betterendisland 1.20-Forge-2.0.6
	- betterfog 1.0.0
	- betterfortresses 1.20-Forge-2.0.6
	- betterjungletemples 1.20-Forge-2.0.5
	- bettermineshafts 1.20-Forge-4.0.4
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- betterwitchhuts 1.20-Forge-3.0.3
	- blockrunner 8.0.4
	- bobberdetector 0.1.9.1.20.1
	- bookshelf 20.2.13
	- botarium 2.3.4
	- callablehorses 1.3.0.1
	- canary 0.3.3
	- carryon 2.1.2.7
	- cavedust 2.0.4
	- chipped 3.0.7
	- citadel 2.6.1
	- cloth_config 11.1.136
	- clumps 12.0.0.4
	- coffee_delight 1.4
	- collective 7.87
	- comforts 6.4.0+1.20.1
	- commongroovylibrary 0.3.3
	- connectivity 1.20.1-5.6
	- connectormod 1.0.0-beta.46+1.20.1
	- controlling 12.0.2
	- copycats 2.1.4+mc.1.20.1-forge
	- corn_delight 1.1.6-1.20.1
	- corpse 1.20.1-1.0.12
	- cosmeticarmorreworked 1.20.1-v1a
	- craftingtweaks 18.2.4
	- create 0.5.1.j
	- create_central_kitchen 1.3.12
	- create_confectionery 1.1.0
	- create_crush_everything 1.0.2
	- create_enchantment_industry 1.2.9.d
	- create_jetpack 4.3.2
	- create_oxidized 0.1.1
	- create_power_loader 1.5.0-mc1.20.1
	- create_recipes 1.0.0
	- create_structures 0.1.1
	- createaddition 1.20.1-1.2.4e
	- createcasing 1.20.1-1.6.2-fix1
	- createchunkloading 1.6.0
	- createcontraptionterminals 1.0.1
	- createdeco 2.0.2-1.20.1-forge
	- createendertransmission 2.0.7-1.20.1
	- createliquidfuel 2.1.1-1.20.1
	- createteleporters 2.2
	- creativecore 2.12.27
	- cristellib 1.1.6
	- ctov 3.4.10
	- cupboard 1.20.1-2.7
	- curios 5.11.0+1.20.1
	- design_decor 0.4.0b
	- deuf 1.20.1-1.3
	- draggable_lists 1.0.1
	- dthexerei 1.20.1-1.2.0
	- dtquark 1.20.1-2.5.3
	- dungeons_arise 2.1.57-1.20.1
	- dynamiccrosshair 9.3
	- dynamiclightsreforged 1.20.1_v1.6.0
	- dynamictrees 1.20.1-1.3.6
	- dynamictreesplus 1.20.1-1.2.0-BETA3
	- eatinganimation 5.0.0
	- effecttooltips 9.0.2
	- effortlessbuilding 3.9
	- embeddium 0.3.31+mc1.20.1
	- emi 1.1.18+1.20.1+forge
	- emi_create_schematics 1.0.1
	- emi_loot 0.7.4+1.20.1+forge
	- emienchants 1.0.0
	- emiffect 1.1.2+mc1.20.1
	- emitrades 1.2.1+mc1.20.1
	- enchdesc 17.1.19
	- endrem 5.3.3-R-1.20.1
	- entity_model_features 2.4.1
	- entity_texture_features 6.2.9
	- entityculling 1.7.2
	- essential 1.3.5.5
	- explorerscompass 1.20.1-1.3.3-forge
	- extendedgears 2.1.1-1.20.1-0.5.1.f-forge
	- extra_shells 1.20.1-v1.0.7
	- fabric_api 0.92.2+1.11.9+1.20.1
	- farmersdelight 1.20.1-1.2.6
	- farsight_view 1.20.1-3.7
	- fastleafdecay 32
	- fastportalsforge 1.0.3
	- ferritecore 6.0.1
	- foodeffecttooltips 1.3.0
	- forge 47.3.12
	- forgeskyboxes 0.0.2-1.20.2
	- forgivingvoid 10.0.1
	- freecam 1.2.1+1.20
	- fsang 9.3.0
	- ftblibrary 2001.2.3
	- ftbquests 2001.4.8
	- ftbteams 2001.3.0
	- ftbxmodcompat 2.1.1
	- fusion 1.1.1
	- fzzy_config 0.5.9+1.20.1+forge
	- gamemenumodoption 2.2.1
	- geckoanimfix 1.0.0
	- geckolib 4.4.9
	- gjeb 1.3.0.32
	- gml 4.0.9
	- gpumemleakfix 1.20.1-1.8
	- gravecore 1.0.5
	- graveht 0.1.1
	- heroes 1.1.83
	- hexerei 1.20.1-0.4.2.2
	- highlighter 1.1.9
	- iammusicplayer 0.5 - Fork of iammusic 3.22.0-alpha.3
	- iceberg 1.1.25
	- immediatelyfast 1.3.3+1.20.4
	- immersive_aircraft 1.1.5+1.20.1
	- immersive_paintings 0.6.7+1.20.1
	- interiors 0.5.6
	- inventoryessentials 8.2.6
	- inventorysorter 23.0.1
	- irisflw 1.1.4
	- itemborders 1.2.2
	- itemfilters 2001.1.0-build.59
	- jade 11.12.2+forge
	- jadeaddons 5.3.1+forge
	- jei 15.20.0.105
	- jeresources 1.4.0.247
	- justenoughprofessions 3.0.1
	- konkrete 1.8.0
	- kotlinforforge 4.11.0
	- kubejs 2001.6.5-build.16
	- leaky 1.20.1-2.1
	- libraryferret 4.0.0
	- lithostitched 1.3.8
	- loadmyresources 1.0.4
	- lootr 0.7.34.85
	- make_bubbles_pop 0.3.0-forge
	- mcwbridges 3.0.0
	- mcwdoors 1.1.1
	- mcwfences 1.1.2
	- mcwfurnitures 3.3.0
	- mcwlights 1.1.0
	- mcwtrpdoors 1.1.4
	- mcwwindows 2.3.0
	- melody 1.0.2
	- minecraft 1.20.1
	- moa_decor_bath 1.20.1
	- moa_decor_toys 1.20.1
	- modernfix 5.19.7+mc1.20.1
	- moonlight 1.20-2.13.40
	- moremobvariants 1.3.0.1
	- mousetweaks 2.25.1
	- mr_cheaper_maps 1.0
	- mr_dungeons_andtaverns 3.0.3.f
	- mr_edf_remastered 4.3
	- mr_no_tooexpensive 0.1
	- mysterious_mountain_lib 1.5.17-1.20.1
	- naturalist 4.0.3
	- naturescompass 1.20.1-1.11.2-forge
	- neruina 2.1.1
	- netherportalspread 8.3
	- nethersdelight 1.20.1-4.0
	- notenoughanimations 1.8.2
	- observable 4.4.2
	- oculus 1.7.0
	- okzoomer 3.0.1
	- openpartiesandclaims 0.23.6
	- otyacraftengine 3.7.0-alpha.2
	- packetfixer 1.4.2
	- palladium 4.1.7
	- pantheonsent 1.1.0
	- parcool 3.3.0.2
	- patchouli 1.20.1-84-FORGE
	- pehkui 3.8.2+1.20.1-forge
	- playeranimator 1.0.2-rc1+1.20
	- plumber_accessories 1.0.0
	- polymorph 0.49.8+1.20.1
	- prism 1.0.5
	- puzzleslib 8.1.25
	- quark 4.0-460
	- quarkoddities 1.20.1
	- railways 1.6.7+forge-mc1.20.1
	- rebind_narrator 2.0.2
	- rechiseled 1.1.6
	- rechiseledcreate 1.0.2
	- recipeessentials 1.20.1-3.5
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.29
	- rhino 2001.2.3-build.6
	- searchables 1.0.3
	- sfcr 1.7.6-mc1.20
	- shoulder_surfing_pehkui_compat 1.0
	- shouldersurfing 1.20.1-4.6.4
	- simplyswords 1.56.0-1.20.1
	- skinnedcarts 2.0.1
	- sliceanddice 3.3.0
	- smallships 2.0.0-b1.4
	- smoothchunk 1.20.1-3.6
	- sophisticatedbackpacks 3.20.5.1044
	- sophisticatedcore 0.6.22.611
	- spyglass_of_curios 1.7.2
	- storagedrawers 12.9.13
	- strawstatues 8.0.3
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17+a
	- supplementaries 1.20-3.1.10
	- suppsquared 1.20-1.1.18
	- t_and_t 0.0NONE
	- tardis_refined 2.0.7
	- tempad 2.3.4
	- tempadwithshaders 1.0.0
	- tia 1.20-1.1
	- toms_storage 1.6.9
	- torchflower_relit 1.0.0
	- torchmaster 20.1.9
	- totw_modded 1.0.5
	- trainperspectivefix 0.0NONE
	- travelerstitles 1.20-Forge-4.0.2
	- villagernames 8.1
	- visible_offhand 1.2.1
	- void_cube 1.3.0
	- weaponmaster_ydm 4.2.3
	- xaerominimap 24.6.1
	- xaeroworldmap 1.39.2
	- xlpackets 1.18.2-2.1
	- yungsapi 1.20-Forge-4.0.6
	- yungsbridges 1.20-Forge-4.0.3
	- yungsextras 1.20-Forge-4.0.3
	- zeta 1.0-24

### Please confirm that you have searched existing issues in the repo.

- [X] Yes, I have checked all open issues and am aware my issue will be closed if it is a duplicate of another

### Please confirm that if your issue is related to rendering, that you have tested without the following before testing; (Shaders, Optifine, Rubidium, embeddium, Sodium)

- [X] Yes, I have done testing without these mods before reported a rendering issue or my issue does not relate to rendering

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/MGQ0BHW5

**Comment by Jeryn99** [comment]
https://github.com/WhoCraft/TardisRefined/releases/tag/v1.20.1-2.1.2


Try this and let me know if it fixes your issue

**Comment by XhRebirth** [comment]
Worked! world launched and I can cycle the console configurator now! :D
