### ISSUE TITLE
Key disappears on Landing Pad

### ISSUE THREAD

**Issue by Bludecoder2** [CommandrMoose/TardisRefined#433]
### Issue description

After I got the upgrade for calling the Tardis with the key once I can't use them on landing Pads anymore.
My key always disappears.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.3.0

### Tardis Refined version

v2.1.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes, I have checked all open issues and am aware my issue will be closed if it is a duplicate of another

### Please confirm that if your issue is related to rendering, that you have tested without the following before testing; (Shaders, Optifine, Rubidium, embeddium, Sodium)

- [X] Yes, I have done testing without these mods before reported a rendering issue or my issue does not relate to rendering

**Comment by Jeryn99** [comment]
Do you have any other mods installed?

**Comment by Bludecoder2** [comment]
> Do you have any other mods installed?

When It happened first yes. But I tested it in a clean new installation with only the Tardis mod and got the same problem.

**Comment by Jeryn99** [comment]
I know this used to be a bug in TriadTech, but I don't see anything in code that would cause damage to the key in the basemod?

**Comment by Bludecoder2** [comment]
I didn't even have triadtech in my modpack. Feels like a priority issue that it uses the key before checking the function of the block. Without the key upgrade the landing pad works fine. I'm trying another new installation. Maybe I left a mod active when I tested earlier.

**Comment by Jeryn99** [comment]
> I didn't even have triadtech in my modpack. Feels like a priority issue that it uses the key before checking the function of the block. Without the key upgrade the landing pad works fine. I'm trying another new installation. Maybe I left a mod active when I tested earlier.

Hold on, we don't have a upgrade for summoning with a key - we only have the landing pad upgrade?

**Comment by Bludecoder2** [comment]
> > I didn't even have triadtech in my modpack. Feels like a priority issue that it uses the key before checking the function of the block. Without the key upgrade the landing pad works fine. I'm trying another new installation. Maybe I left a mod active when I tested earlier.
> 
> Hold on, we don't have a upgrade for summoning with a key - we only have the landing pad upgrade?

You're right I just checked. I forgot that that upgrade was in triadtech, which I do have installed. My mistake.

**Comment by Jeryn99** [comment]
I'll nudge you in the right direction: https://github.com/ThreeTAG/TriadTech/issues/new
