### ISSUE TITLE
Tardis Shell Viewer not in correct position

### ISSUE THREAD

**Issue by The-Rose-Composer** [CommandrMoose/TardisRefined#434]
### Issue description

When you use the Tardis Shell viewer to view the exterior of the Tardis, two problems will arise. While the Tardis is landed, two different Tardis's will be rendered. I think this is how it is meant to be coded, but where the trouble starts is that one of the two Tardis's meant to be rendered will not be in the same spot as the other (see attached screenshot for visual). I'm pretty sure they are supposed to overlap and only one should be visible at a time, but one Tardis is rendered about two blocks off from the other one. 
This glitch does not differ depending on what exterior you have selected.

The second half to this is that after exiting the Shell Viewer (pressing tab), it is supposed to put you back in the Tardis console room at the coordinates that you entered into the viewer, but instead it will send you to those coordinates in the overworld. (Say you click on the monitor and enter into the viewer inside the Tardis at X:1 Y:100 Z:1 and then exit the viewer, it will put you at X:1 Y:100 Z:1 in the over

### Steps to reproduce

1. Enter into the Tardis Shell Viewer and move the camera around, you will notice that the two different Tardis's that are rendered on two different blocks.
2. Exit the shell viewer and you will now be in the overworld. If your Tardis was in flight when you entered into the viewer, you can only get back with commands.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.3.0

### Tardis Refined version

v2.1.1

### Other relevant versions

THIS IS NOT FOR v2.1.1 IT IS FOR v2.1.2
(Sorry I didn't know where else to put this :P)

### Please confirm that you have searched existing issues in the repo.

- [ ] Yes, I have checked all open issues and am aware my issue will be closed if it is a duplicate of another

### Please confirm that if your issue is related to rendering, that you have tested without the following before testing; (Shaders, Optifine, Rubidium, embeddium, Sodium)

- [ ] Yes, I have done testing without these mods before reported a rendering issue or my issue does not relate to rendering

**Comment by The-Rose-Composer** [comment]
Not sure why but it appears to have removed half of the report, I'll attach the screenshots here and finish that sentence. 
"(Say you click on the monitor and enter into the viewer inside the Tardis at X:1 Y:100 Z:1 and then exit the viewer, it will put you at X:1 Y:100 Z:1 in the overworld)"
![2024-12-28_18 13 18](https://github.com/user-attachments/assets/815c1cb9-6123-4561-ae43-cd35b7883787)
![2024-12-28_18 23 30](https://github.com/user-attachments/assets/9f169e66-0b96-497d-91db-61294045b447)

**Comment by Jeryn99** [comment]
Fixed
