### ISSUE TITLE
Game crashes upon selecting a new shell (not confirming)

### ISSUE THREAD

**Issue by undertalenerd** [CommandrMoose/TardisRefined#436]
### Issue description

Selecting shell should display a preview, but instead crashes the game.

### Steps to reproduce

1. Enter computer bank
2. Go to shells
3. Click on any shell

### Minecraft version

1.20.1

### Mod Loader Platform type

Fabric

### Mod Loader version

0.16.9

### Tardis Refined version

v2.1.2

### Other relevant versions

I have the Extra Shells mod installed as well.

### Mod List

![image](https://github.com/user-attachments/assets/67712ab7-b863-4000-ab1b-797a3fa45d66)
![image](https://github.com/user-attachments/assets/012be3b9-4f25-4968-9641-8c5a3a157b61)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes, I have checked all open issues and am aware my issue will be closed if it is a duplicate of another

### Please confirm that if your issue is related to rendering, that you have tested without the following before testing; (Shaders, Optifine, Rubidium, embeddium, Sodium)

- [X] Yes, I have done testing without these mods before reported a rendering issue or my issue does not relate to rendering

**Comment by Jeryn99** [comment]
I require the crash report

**Comment by undertalenerd** [comment]
It was my bad, I forgot to add Extra Shells to the server mods.
