### ISSUE TITLE
tardis concole can be pushed with a piston.

### ISSUE THREAD

**Issue by TheRealAaronPrince** [CommandrMoose/TardisRefined#437]
### Issue description

tardis concole can be pushed with a piston, which causes duplicate collision box and buttons.

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

47.3.0

### Tardis Refined version

v2.1.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes, I have checked all open issues and am aware my issue will be closed if it is a duplicate of another

### Please confirm that if your issue is related to rendering, that you have tested without the following before testing; (Shaders, Optifine, Rubidium, embeddium, Sodium)

- [X] Yes, I have done testing without these mods before reported a rendering issue or my issue does not relate to rendering

**Comment by Jeryn99** [comment]
Incredible
