### ISSUE TITLE
tardis refind console change game crash

### ISSUE THREAD

**Issue by generalkenobixkorra** [CommandrMoose/TardisRefined#439]
### Issue description

when i try to change the tardis console the game crashes

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

forge

### Tardis Refined version

v2.1.1

### Other relevant versions

this ver of tardis refind is very buggy like tardis console it crashes your game

### Please confirm that you have searched existing issues in the repo.

- [X] Yes, I have checked all open issues and am aware my issue will be closed if it is a duplicate of another

### Please confirm that if your issue is related to rendering, that you have tested without the following before testing; (Shaders, Optifine, Rubidium, embeddium, Sodium)

- [X] Yes, I have done testing without these mods before reported a rendering issue or my issue does not relate to rendering

**Comment by Jeryn99** [comment]
Already fixed, official release in a few days
Download from here for now: https://github.com/WhoCraft/TardisRefined/releases/tag/v1.20.1-2.1.2

Also, in future, upload a crash report else you might aswell be telling me nothing

**Comment by generalkenobixkorra** [comment]
will you add the patch in curseforge ?

**Comment by Jeryn99** [comment]
Like I said above:
> Already fixed, official release in a few days
