### ISSUE TITLE
Recipes and Items missing (1.20.1 Forge)

### ISSUE THREAD

**Issue by antonhibl** [CommandrMoose/TardisRefined#440]
### Issue description

The mod is missing recipes such as the recipe for the terraformer as well as several item's like the artron pillars just don't exist at all. You cannot even give them to the player with commands. This is all happening in the 1.20.1 Forge version of the mod

### Steps to reproduce

1. Install mod on 1.20.1 
2. try to craft terraformer
3. tfw no recipe exists
4. give yourself one and throw materials in fire
5. make tardis
6. realize there is no artron pillars, I can't even find them with commands
7. come here

### Minecraft version

1.20.1

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 47.3.0

### Tardis Refined version

v2.1.1

### Mod List

Abridged
Advancement Plaques
Almanac
AppleSkin
Architectury
Bad Packets
Bag Of Holding
Balm
Bartering Station
Better Amethyst
Better Combat
Better Tridents
Biospherical Expansion
Block Runner
Botarium
Caelus API
Cave Dust
Citadel
Clear Water
Cloth Config v10 API
CoFH Core
ColossalChests
Comforts
Create
Create : Encased
Create Crafts & Additions
Create Enchantment Industry
Create Goggles
Create Mechanical Spawner
Create: Aquatic Ambitions
Create: Connected
Create: Steam 'n' Rails
Create: Structures
Creeper Overhaul
Cristel Lib
Cupboard utilities
Curios API
Cut Through
Cyclops Core
Draggable Lists
Dungeon Now Loading
Dungeons and Taverns
Dungeons and Taverns Ancient City Overhaul
Dynamic Crosshair
Easy Anvils
Easy Magic
Easy Shulker Boxes
Ecospherical Expansion
Effect Descriptions
Elytra Slot
Embeddium
Embeddium Extra
Embeddium++
Ender Trigon
Enlightend
EntityCulling
Every Compat
Explorer's Compass
Explorify
Extended Cogwheels
FallingTree
Farsight mod
Ferrite Core
Forgified Fabric API
Framework
Fusion
GeckoLib 4
GeckoLibIrisCompat
GlitchCore
Held Item Tooltips
Heracles
Hex Casting
HexDebug
HopoBetterMineshaft
HopoBetterRuinedPortals
HopoBetterUnderwaterRuins
Horse Expert
Hourglass
Iceberg
ImmediatelyFast
Incendium
Inline
Inventory Essentials
It Takes A Pillage
Jade
Journeymap
Just Enough Effects Descriptions
Just Enough Items
Just Enough Resources
Key Binding Patch
Kotlin for Forge
KubeJS
KubeJS Addditions (Forge)
KubeJS Create
KubeJS Thermal
Legendary Tooltips
Let Me Despawn
Load My F***ing Tags
Loot Journal
LootJS
Lootr
Memory Leak Fix
Mineblock's Repeated Utilities
Model Gap Fix
Moderately Enough Effect Descriptions
ModernFix
Molten Metals
Moog's End Structures
Moonlight Library
MoreJS
Mouse Tweaks
Moyai
Mystical Oak Tree
Naturalist
Nature's Compass
No Chat Reports
Nullscape
Obscure API
Overflowing Bars
PAUCAL
Paper Doll
Patchouli
Pehkui
Phantasmic
Player Animator
Polymorph
PonderJS
Prism
Puzzles Lib
Randomium
Rechiseled
Rechiseled: Create
Redstone Arsenal
Regeneration
Resourceful Lib
Resourcefulconfig
Rhino
STRAYED FATES: Forsaken
Scorched Guns
Scorched Guns Brass
ServerCore
Simple Inventory Sorter (Configurable)
Simple Voice Chat
Sodium Dynamic Lights
Sodium Options API
Sound Physics Remastered
Sounds
Starlight
Stone Zone
Stoneworks
Structure Gel API
Stylish Effects
Subterrestrial
SuperFancyClouds: Rearchitected
SuperMartijn642's Config Library
SuperMartijn642's Core Lib
TARDIS Refined
Temporal API
Thermal Cultivation
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Thermal Innovation
Thermal Integration
Thermal Locomotion
Towns and Towers
Trading Post
Traveler's Titles
TreePlacer
Trolldom
UniLib
V-Minus
WF's Cave Overhaul
When Dungeons Arise
YUNG's API
YUNG's Better Desert Temples
YUNG's Better End Island
YUNG's Better Jungle Temples
YUNG's Better Mineshafts
YUNG's Better Nether Fortresses
YUNG's Better Ocean Monuments
YUNG's Better Strongholds
YUNG's Better Witch Huts
YUNG's Bridges
YUNG's Extras
YetAnotherConfigLib
create: things and misc
mutil

### Please confirm that you have searched existing issues in the repo.

- [X] Yes, I have checked all open issues and am aware my issue will be closed if it is a duplicate of another

### Please confirm that if your issue is related to rendering, that you have tested without the following before testing; (Shaders, Optifine, Rubidium, embeddium, Sodium)

- [X] Yes, I have done testing without these mods before reported a rendering issue or my issue does not relate to rendering

**Comment by Jeryn99** [comment]
Do you mean crafting table recipes....?

**Comment by Jeryn99** [comment]
You may need to read our wiki a little closer:

Crafting Process: https://wiki.tardisrefined.net/astral-manipulator-crafting.html
Crafting Recipe: https://wiki.tardisrefined.net/astral-manipulator-recipes.html#terraformer

**Comment by antonhibl** [comment]
omg I completely missed that, i'm so sorry

**Comment by Jeryn99** [comment]
No worries, enjoy!
