### ISSUE TITLE
[BUG] Console suffocating

### ISSUE THREAD

**Issue by Bug1312** [CommandrMoose/TardisRefined#47]
**Describe the bug**
When placing blocks above the console unit (where a control unit would reside), you will here the entity hurt sound effect. After a while, the entity will eventually die from suffocation.

**To Reproduce**
1. Place a `tardis_console` block
2. Place a block at the player's head height 1 block away from the center of the console on a side that a control is present.
3. Observe sound / See error
4. Set health lower of control entity with commands / wait
3. Observe death / See error

**Expected behavior**
The control should not be able to suffocate. 

**Screenshots**
![2023-01-03_20 18 53](https://user-images.githubusercontent.com/59811382/210467125-85c46e93-00cf-4f83-87f7-1eb388ff6cb1.png)

**Platform:**
 - MC 1.19.2
 - Fabric 0.14.12

**Comment by thejudge156** [comment]
I think they forgot to prevent control entity suffocation

**Comment by Suff99** [comment]
We use living entity’s as we are investigating a issue with the entity class. Issues like this will not occur after those changes are implemented
