### ISSUE TITLE
[BUG] Controls die and respawn when loading chunks

### ISSUE THREAD

**Issue by Bug1312** [CommandrMoose/TardisRefined#49]
**Describe the bug**
When loading a chunk quickly enough, the console_control entity will die, as it's a living entity currently it will play a sound and particles. It will then respawn as if nothing happened.

**To Reproduce**
- Dimension traversal
 1. Place a console in a non-tardis dimension
 2. Place TARDIS nearby, enough to be close when you exit
 3. Enter TARDIS
 4. Leave TARDIS
 5. See error
- Teleportation
 1. Place a console in a non-tardis dimension
 2. Teleport far away (1000 blocks will suffice)
 3. Teleport back
 4. See Error

**Expected behavior**
No sounds, particles, etc should be played **or** the control shouldn't kill itself.

**Screenshots**
![2023-01-03_20 35 52](https://user-images.githubusercontent.com/59811382/210469013-bf6e8226-5f7f-4c1f-8172-6de65b994b4f.png)

**Platform:**
- MC 1.19.2
- Fabric 0.14.12

**Additional context**
In my reproduce I mention a non-tardis dimension. This bug does not seem to be occuring in a tardis dimension.
When travelling via portals, results are mixed, perhaps from computer speed.

**Comment by CommandrMoose** [comment]
Thanks for the report, this was a known issue as we were experiencing issues with certain entity behaviors. Consider this fixed.
