### ISSUE TITLE
Immersive portals cause the Tardis dimension to disappear

### ISSUE THREAD

**Issue by TheX39** [CommandrMoose/TardisRefined#69]
[crash-2023-01-14_18.45.35-server.txt](https://github.com/CommandrMoose/TardisRefined/files/10418573/crash-2023-01-14_18.45.35-server.txt)
### Issue description

When you have both the Tardis mod and immersive portals installed. it causes the Tardis dimension to completely disappear and when entering the dimension it crashes the game with the "missing Dimension" error.

### Steps to reproduce

1. Have both immersive portals and Tardis Refined
2. create a new world
3. place the tardis seed block to grow into the tardis
4. go into the tardis
5. The Game will crash with "missing dimension" error

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

quilt-loader-17.9-beta-1.19.2

### Tardis Refined version

Pre-release v0.1

**Comment by Suff99** [comment]
Already fixing in upcoming IP integration update.
