### ISSUE TITLE
Terraforming not working 

### ISSUE THREAD

**Issue by CosmicPanda03** [CommandrMoose/TardisRefined#74]
### Issue description

When I build the terraforming Platform and place it inside the cave, it doesn’t respond at all

### Steps to reproduce

1. Build the Tardis cave

2. Place the copper in a circle shape with redstone block in the middle.

3. Place the terraformer on top of red stone block

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.14.12

### Tardis Refined version

Pre-release v0.1

**Comment by AlienXtream** [comment]
you need un waxed, un oxidised copper blocks. has to specifically be the one you get when you craft 9 ingots together. no other variants will work

**Comment by CommandrMoose** [comment]
The terraforming process requires pure Copper blocks. Please ensure that you are using the correct resources.

Closing this issue, please re-open this if this problem persists.
