### ISSUE TITLE
[Bug] Shell cloning

### ISSUE THREAD

**Issue by AlienXtream** [CommandrMoose/TardisRefined#76]
### Issue description

it is possible to duplicate the exterior shell by repeatedly activating the throttle while landing/taking off. duplicate shells retain tardis ID but loose all other notable functionality aside from inability to remove via creative mode (requires /fill or world edit //replace to remove). they do not respond to block updates nor moving the tardis a short distance away

### Steps to reproduce

take off
hold RMB on throttle (or spam click)
should notice several "landing sounds" play consecutively without take off
exit tardis should reveal a stack of shells.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

NA

### Tardis Refined version

Pre-release v0.1

**Comment by CommandrMoose** [comment]
This issue has been addressed in the [newest changes to flight mechanics](564e9bcd4dbbf1aa1392f37b49e82ae5b2ac893d) (upcoming update.) Thank you for the report.
