### ISSUE TITLE
[Bug] Console configurator can be used to break unbreakable blocks.

### ISSUE THREAD

**Issue by WoahItsKarma** [CommandrMoose/TardisRefined#80]
### Issue description

Title says everything, example images below.

![2023-01-26_19 10 05](https://user-images.githubusercontent.com/85769531/214928540-bac3f4b5-d0bf-4c78-95ef-d2ede7ea8cb6.png)
![2023-01-26_19 10 07](https://user-images.githubusercontent.com/85769531/214928554-40e144a4-c8a4-4d90-aeda-b627b4b1d689.png)
![2023-01-26_19 09 42](https://user-images.githubusercontent.com/85769531/214928582-feaa229f-1fd9-4463-a9ef-bf4bac1289a3.png)
![2023-01-26_19 09 46](https://user-images.githubusercontent.com/85769531/214928594-f69d7697-9ffa-4ba1-a41b-3b2de2588a43.png)
![2023-01-26_19 10 22](https://user-images.githubusercontent.com/85769531/214928607-d59b47da-7b5c-4588-9faf-a241db92d5ac.png)
![2023-01-26_19 10 29](https://user-images.githubusercontent.com/85769531/214928614-ef4be321-4d57-4332-bc82-1c881ea38573.png)

### Steps to reproduce

1. Place a Console Configurator in front of an unbreakable block
2. Right click the Configurator with an Iron block to generate a Console
3. The Console will have replaced the unbreakable block.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric 0.14.12

### Tardis Refined version

Pre-release v0.1

### Other relevant versions

'Prolly the same on the forge version but checking ain't my problem.

**Comment by CommandrMoose** [comment]
Thank you for the report. This issue has been addressed and will be resolved in the next release.

Fixed in commit: https://github.com/CommandrMoose/TardisRefined/commit/564e9bcd4dbbf1aa1392f37b49e82ae5b2ac893d#diff-f7b904918300624fce0217f407e1f487e58c63b34e7054ce5b530b24fe3a1371
