### ISSUE TITLE
My Game Craches

### ISSUE THREAD

**Issue by The10thDoctor1** [CommandrMoose/TardisRefined#81]
### Issue description

My game Craches if i go into a TARDIS Root 

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

0.14.12

### Tardis Refined version

Pre-release v0.1

### Other relevant versions

immersive-portals-2.2.5-mc1.19.2-fabric.jar

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://gist.github.com/The10thDoctor1/4e88cf839412778de4843db21104e990

**Comment by Suff99** [comment]
The mod is not currently designed to work with Immersive Portals in it's current released state. Please wait for the next update for Immersive Portals integrations and compatibility.
