### ISSUE TITLE
[Crash] "unexpected" entry method crash

### ISSUE THREAD

**Issue by AlienXtream** [CommandrMoose/TardisRefined#82]
### Issue description

on some occasions entering the tardis by "abstract" or "unespected" ways can trigger a crash. specifically i have step assist and it seems walking into the collision more than once before it loads can trigger it.

*file too big for paste bin* >512KB >.<
[crash-2023-02-01_07.59.57-server.txt](https://github.com/CommandrMoose/TardisRefined/files/10551003/crash-2023-02-01_07.59.57-server.txt)

### Steps to reproduce

start by having a tardis facing the player in the orange box depicted below with the showl scenario.
apply some step height modofication (be that via another mod or directly adjusting the step height in your dev environment)
walk around a bit, attempting to enter the tardis from various ways. 
hopefully it will trigger a crash that you can work backwards from to try and fix. 

![image](https://user-images.githubusercontent.com/12606809/215883800-80381348-0bfc-4a5a-8f56-7a3ce78bf727.png)

it is possible there are other core mod interactions that are causing this to happen however i dont see anything in the crash report that would suggest that. can do additional testing if you are unable to reproduce in dev.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

forge 43.2.3

### Tardis Refined version

Pre-release v0.1

**Comment by CommandrMoose** [comment]
Thanks for this report, the detail helps a lot. We'll look into this.

**Comment by AlienXtream** [comment]
hey, im no noob at bug reports ;)

**Comment by AlienXtream** [comment]
seems to be fixed as of v1
