### ISSUE TITLE
[BUG] Experience clears upon entering or leaving the TARDIS

### ISSUE THREAD

**Issue by SubsonicSabre** [CommandrMoose/TardisRefined#86]
### Issue description

Upon entering or leaving the TARDIS, my experience appears to reset to 0. Upon gaining more it returns, but while it is visually gone it is also functionally gone (cannot use enchanting table, etc.). Regenerations from the Regeneration mod also reset under the same conditions, but I don't know if this is the place for that.

### Steps to reproduce

1. Gain experience
2. Enter TARDIS
3. See experience reset
4. Gain more experience
5. See previous experience in addition to experience gained in Step 4
6. Exit TARDIS
7. See experience reset again.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader Version 0.14.13

### Tardis Refined version

Pre-release v0.1

**Comment by AlienXtream** [comment]
vanilla MC bug caused by this: https://bugs.mojang.com/browse/MC-124177
causes other affects to reset too. happens with endportal sometimes too

**Comment by Suff99** [comment]
This bug is on Mojang, but the regeneration one should be filed on the regeneration issue tracker :)
