### ISSUE TITLE
Wrong height tardis?

### ISSUE THREAD

**Issue by Biemeneer** [CommandrMoose/TardisRefined#92]
### Issue description

I'm not sure if this is an actual issue but it looked really weird when i was playing with this mod, whenever i jumped against the tardis i would jump on top of it and half my body would be inside the tardis because the tardis is 1 block tall but the model is 2. I'm not sure if this is intentional but I'm writing it here because it looked weird.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric loader version 0.14.12

### Tardis Refined version

Pre-release v0.1

**Comment by Suff99** [comment]
I raised this concern also - it’s since been altered to be the same as a slab hit box so as to make it less noticeable
