### ISSUE TITLE
Incompatibility with Ars Magica: Legacy

### ISSUE THREAD

**Issue by Swift2337** [CommandrMoose/TardisRefined#94]
### Issue description

This issue crashes the game when terraforming a tardis root shell with the Ars Magica: Legacy mod installed. Removing the mod fixes the crashing issue, and you can create a tardis perfectly fine without it.

### Steps to reproduce

Create a tardis root shell, and create the terraform multi-block structure. 
Leave the tardis root shell, and the game crashes.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

43.2.4

### Tardis Refined version

Pre-release v0.1

### Other relevant versions

arsmagicalegacy-1.19.2-1.2.4.jar

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/5BH7SYXu

**Comment by 50ap5ud5** [comment]
This seems to be related to the way we defined the Control Entities.

The ARS Magica Legacy mod is applying some modifications to the EntityAttributes of all Living Entities

In the current pre release version, they are classified as Living Entities, which most mob entities are apart of. Additionally, we did not define the EntityAttributes in a conventional way, which may have caused ARS Magica to not know how to handle this. 

We have made changes to the way Control Entities work in the next release, which should mitigate this issue, as it will no longer be a LivingEntity, and thus not be affected by ARS Magica's modifications. I'm going to mark this issue as resolved.

Please feel free to re-open this issue if it persists in the next version.
